<font color=#760202><center><h1>Projet 4</h1></center> <center><h3>Réalisez une étude de santé publique</h3></center> 



&nbsp;

## <font color=#2921CA> I - Importation, nettoyage et formatage    
&nbsp;  
**Etape 1 :** 
    
**Importation de la librairie pandas et des 4 fichiers CSV fournis en PJ** 

    


In [1]:
import pandas as pd

In [2]:
dispo = pd.read_csv("C:\\Users\\narab\\OneDrive\\Documents\\OpenClassRooms\\Projet 4\\Nouveau Dossier\\dispo_alimentaire.csv")
aide = pd.read_csv("C:\\Users\\narab\\OneDrive\\Documents\\OpenClassRooms\\Projet 4\\Nouveau Dossier\\aide_alimentaire.csv")
pop = pd.read_csv("C:\\Users\\narab\\OneDrive\\Documents\\OpenClassRooms\\Projet 4\\Nouveau Dossier\\population.csv")
nutri = pd.read_csv("C:\\Users\\narab\\OneDrive\\Documents\\OpenClassRooms\\Projet 4\\Nouveau Dossier\\sous_nutrition.csv")

**Etape 2 :**

**A faire pour chacun des fichiers importés :**

- Un aperçu et une vérification de la forme du fichier, des informations principales, des types des variables, etc...


- Des modifications sur le nom des variables si nécessaire


- Des modifications des types et des ordres de grandeurs des données si nécessaire


- Une identification des variables communes entre les fichiers pour des futures jointures



&nbsp;

###  <font color=#009F0C> A - Dataframe "dispo" 
<font color=#009F0C> (année 2013)
       
&nbsp;

In [3]:
dispo.head()

Zone                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

In [4]:
dispo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15605 entries, 0 to 15604
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Zone                                                           15605 non-null  object 
 1   Produit                                                        15605 non-null  object 
 2   Origine                                                        15605 non-null  object 
 3   Aliments pour animaux                                          2720 non-null   float64
 4   Autres Utilisations                                            5496 non-null   float64
 5   Disponibilité alimentaire (Kcal/personne/jour)                 14241 non-null  float64
 6   Disponibilité alimentaire en quantité (kg/personne/an)         14015 non-null  float64
 7   Disponibilité de matière grasse en quantité (g/personne/jo

In [5]:
dispo.describe(include = "all")

Zone           Produit   Origine  Aliments pour animaux  \
count   15605             15605     15605            2720.000000   
unique    174                98         2                    NaN   
top      Inde  Abats Comestible  vegetale                    NaN   
freq       97               174     11896                    NaN   
mean      NaN               NaN       NaN             479.501838   
std       NaN               NaN       NaN            4240.119637   
min       NaN               NaN       NaN               0.000000   
25%       NaN               NaN       NaN               0.000000   
50%       NaN               NaN       NaN               4.000000   
75%       NaN               NaN       NaN              74.000000   
max       NaN               NaN       NaN          150000.000000   

        Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
count           5496.000000                                    14241.000000   
unique                  NaN                                             NaN   
top                     NaN                                             NaN   
freq                    NaN                                             NaN   
mean             157.391376                                       34.789832   
std             5076.785816                                      107.287655   
min                0.000000                                      -21.000000   
25%                0.000000                                        0.000000   
50%                0.000000                                        4.000000   
75%                4.000000                                       21.000000   
max           347309.000000                                     1711.000000   

        Disponibilité alimentaire en quantité (kg/personne/an)  \
count                                        14015.000000        
unique                                                NaN        
top                                                   NaN        
freq                                                  NaN        
mean                                             8.719368        
std                                             24.618223        
min                                             -1.930000        
25%                                              0.060000        
50%                                              0.830000        
75%                                              5.190000        
max                                            430.760000        

        Disponibilité de matière grasse en quantité (g/personne/jour)  \
count                                        11794.000000               
unique                                                NaN               
top                                                   NaN               
freq                                                  NaN               
mean                                             1.283111               
std                                              3.680399               
min                                             -0.030000               
25%                                              0.010000               
50%                                              0.080000               
75%                                              0.630000               
max                                             60.760000               

        Disponibilité de protéines en quantité (g/personne/jour)  \
count                                        11561.000000          
unique                                                NaN          
top                                                   NaN          
freq                                                  NaN          
mean                                             1.223608          
std                                              3.598686          
min                                             -0.370000          
25%                          

In [6]:
dispo["Zone"].unique()

array(['Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne',
       'Angola', 'Antigua-et-Barbuda', 'Arabie saoudite', 'Argentine',
       'Arménie', 'Australie', 'Autriche', 'Azerbaïdjan', 'Bahamas',
       'Bangladesh', 'Barbade', 'Belgique', 'Belize', 'Bermudes',
       'Bolivie (État plurinational de)', 'Bosnie-Herzégovine',
       'Botswana', 'Brunéi Darussalam', 'Brésil', 'Bulgarie',
       'Burkina Faso', 'Bélarus', 'Bénin', 'Cabo Verde', 'Cambodge',
       'Cameroun', 'Canada', 'Chili', 'Chine - RAS de Hong-Kong',
       'Chine - RAS de Macao', 'Chine, Taiwan Province de',
       'Chine, continentale', 'Chypre', 'Colombie', 'Congo', 'Costa Rica',
       'Croatie', 'Cuba', "Côte d'Ivoire", 'Danemark', 'Djibouti',
       'Dominique', 'El Salvador', 'Espagne', 'Estonie', 'Eswatini',
       'Fidji', 'Finlande', 'France', 'Fédération de Russie', 'Gabon',
       'Gambie', 'Ghana', 'Grenade', 'Grèce', 'Guatemala', 'Guinée',
       'Guinée-Bissau', 'Guyana', 'Géorgie', 'H

&nbsp;

**Pour "dispo" :**


- Après avoir vérifié les différentes valeurs de la colonne "Zone", je la renomme en "Pays" par choix préférentiel


- Les types des variables sont conformes aux attentes, il n'y a rien de particulier à signaler


In [7]:
dispo.rename(columns = {"Zone":"Pays"}, inplace = True)
dispo.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

&nbsp;

### <font color=#009F0C> B - Dataframe "aide"
    
&nbsp;    

In [8]:
aide.head()

Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [9]:
aide.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Pays bénéficiaire  1475 non-null   object
 1   Année              1475 non-null   int64 
 2   Produit            1475 non-null   object
 3   Valeur             1475 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 46.2+ KB


In [10]:
aide.describe(include = "all")

Pays bénéficiaire        Année       Produit         Valeur
count               1475  1475.000000          1475    1475.000000
unique                76          NaN            16            NaN
top              Algérie          NaN  Non-céréales            NaN
freq                  39          NaN           220            NaN
mean                 NaN  2014.054237           NaN    7481.966780
std                  NaN     0.946916           NaN   23339.531424
min                  NaN  2013.000000           NaN       0.000000
25%                  NaN  2013.000000           NaN     287.500000
50%                  NaN  2014.000000           NaN    1178.000000
75%                  NaN  2015.000000           NaN    4334.500000
max                  NaN  2016.000000           NaN  265013.000000

**Pour "aide" :** 

- Je renomme la colonne "Pays Bénéficiare" en "Pays" qui sera potentiellement une clé commune avec "dispo"


- Je renomme également "Valeur" en "Quantité aide alimentaire (tonnes)" par nécessité d'explicité 


- J'identifie que les valeurs "Année" sont de type int64 (quantitatives), je modifie le type de cette colonne en category pour les tranformer en valeurs qualitatives

In [11]:
aide.rename(columns = {"Pays bénéficiaire" : "Pays"}, inplace = True)
aide.rename(columns = {"Valeur" : "Quantité aide alimetaire (tonnes)"}, inplace = True)
aide["Année"] = aide["Année"].astype("category")
aide.head()

Pays Année              Produit  Quantité aide alimetaire (tonnes)
0  Afghanistan  2013  Autres non-céréales                                682
1  Afghanistan  2014  Autres non-céréales                                335
2  Afghanistan  2013         Blé et Farin                              39224
3  Afghanistan  2014         Blé et Farin                              15160
4  Afghanistan  2013             Céréales                              40504

In [12]:
aide.describe(include = "all")

Pays   Année       Produit  Quantité aide alimetaire (tonnes)
count      1475  1475.0          1475                        1475.000000
unique       76     4.0            16                                NaN
top     Algérie  2013.0  Non-céréales                                NaN
freq         39   519.0           220                                NaN
mean        NaN     NaN           NaN                        7481.966780
std         NaN     NaN           NaN                       23339.531424
min         NaN     NaN           NaN                           0.000000
25%         NaN     NaN           NaN                         287.500000
50%         NaN     NaN           NaN                        1178.000000
75%         NaN     NaN           NaN                        4334.500000
max         NaN     NaN           NaN                      265013.000000

In [13]:
aide.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype   
---  ------                             --------------  -----   
 0   Pays                               1475 non-null   object  
 1   Année                              1475 non-null   category
 2   Produit                            1475 non-null   object  
 3   Quantité aide alimetaire (tonnes)  1475 non-null   int64   
dtypes: category(1), int64(1), object(2)
memory usage: 36.3+ KB


&nbsp;

### <font color=#009F0C> C - Dataframe "pop"
    
&nbsp;    

In [14]:
pop.head()

Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [15]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Zone    1416 non-null   object 
 1   Année   1416 non-null   int64  
 2   Valeur  1416 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 33.3+ KB


In [16]:
pop.describe(include = "all")

Zone        Année        Valeur
count          1416  1416.000000  1.416000e+03
unique          236          NaN           NaN
top     Afghanistan          NaN           NaN
freq              6          NaN           NaN
mean            NaN  2015.500000  3.144793e+04
std             NaN     1.708428  1.300812e+05
min             NaN  2013.000000  7.930000e-01
25%             NaN  2014.000000  3.783410e+02
50%             NaN  2015.500000  5.126480e+03
75%             NaN  2017.000000  1.930666e+04
max             NaN  2018.000000  1.427648e+06

**Pour "pop" :**

- Je renomme "Zone" en "Pays" (potentielle clé commune avec "dispo" et "aide")


- Je renomme "Valeur" en "Population (milliers)"


- Je transforme le type de "Année", initialement int64, en category (également potentielle clé commune avec "aide")


In [17]:
pop.rename(columns = {"Zone" : "Pays"}, inplace = True)
pop.rename(columns = {"Valeur" : "Population (milliers)"}, inplace = True)
pop["Année"] = pop["Année"].astype("category")
pop.head()

Pays Année  Population (milliers)
0  Afghanistan  2013              32269.589
1  Afghanistan  2014              33370.794
2  Afghanistan  2015              34413.603
3  Afghanistan  2016              35383.032
4  Afghanistan  2017              36296.113

In [18]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   Pays                   1416 non-null   object  
 1   Année                  1416 non-null   category
 2   Population (milliers)  1416 non-null   float64 
dtypes: category(1), float64(1), object(1)
memory usage: 23.8+ KB


In [19]:
pop.describe(include = "all")

Pays   Année  Population (milliers)
count          1416  1416.0           1.416000e+03
unique          236     6.0                    NaN
top     Afghanistan  2013.0                    NaN
freq              6   236.0                    NaN
mean            NaN     NaN           3.144793e+04
std             NaN     NaN           1.300812e+05
min             NaN     NaN           7.930000e-01
25%             NaN     NaN           3.783410e+02
50%             NaN     NaN           5.126480e+03
75%             NaN     NaN           1.930666e+04
max             NaN     NaN           1.427648e+06

&nbsp;

### <font color=#009F0C> D - Dataframe "nutri"
    
&nbsp;    

In [20]:
nutri.head()

Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [21]:
nutri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  624 non-null    object
dtypes: object(3)
memory usage: 28.7+ KB


In [22]:
nutri.describe(include = "all")

Zone      Année Valeur
count          1218       1218    624
unique          203          6    139
top     Afghanistan  2012-2014   <0.1
freq              6        203    120

In [23]:
nutri["Année"].unique()

array(['2012-2014', '2013-2015', '2014-2016', '2015-2017', '2016-2018',
       '2017-2019'], dtype=object)

In [24]:
nutri["Valeur"].unique()

array(['8.6', '8.8', '8.9', '9.7', '10.5', '11.1', '2.2', '2.5', '2.8',
       '3', '3.1', '3.3', '0.1', '1.3', '1.2', nan, '7.6', '6.2', '5.3',
       '5.6', '5.8', '5.7', '1.5', '1.6', '1.1', '1.7', '<0.1', '21.7',
       '22.4', '23.3', '22.3', '21.5', '20.9', '0.8', '2', '1.9', '1.8',
       '0.4', '0.5', '0.3', '0.2', '3.2', '3.4', '3.6', '3.8', '2.1',
       '2.3', '2.4', '0.6', '0.7', '0.9', '3.9', '2.7', '1.4', '4.8',
       '4.6', '4.9', '5', '4.4', '4.3', '4.2', '4.5', '26.2', '24.3',
       '21.3', '21.1', '2.9', '5.1', '5.2', '5.4', '203.8', '198.3',
       '193.1', '190.9', '190.1', '189.2', '23.6', '24', '24.1', '3.7',
       '7.3', '7.8', '8.4', '9', '9.1', '10.1', '10', '10.7', '11.5',
       '11.9', '11.8', '8.7', '10.3', '11', '1', '5.5', '6.8', '7.9',
       '5.9', '7', '9.2', '9.4', '9.6', '6.7', '7.1', '7.2', '14.7',
       '17.4', '20.2', '22.2', '22.8', '24.6', '31.1', '28.5', '25.4',
       '24.8', '26.1', '14.5', '15.4', '16.5', '15.8', '15.7', '10.8',
       '

**Pour "nutri" :**

- Je renomme "Zone" en "Pays" (potentielle clé commune avec "dispo", "aide" et "pop")


- Ici il y a la colonne "Année" présentant des valeurs sous forme d'intervalle d'années. Il y a 6 intervalles disctincts de 3 années chacun, je change ces valeurs par la moyenne de ces années (cf notes de Julien), ainsi "Année" pourra également être une clé commune avec "aide" et "pop"


- Je remarque que la "Valeur" est de type object que je vais convertir en numeric. La conversion ne peut pas s'effectuer directement car il y a des valeurs = "<0.1". Je vais remplacer toutes valeurs "<0.1" par "0" en estimant qu'elles correspondent à des valeurs négligeables pour la suite de l'étude.


- J'effectue un produit de "Valeur" par 1000 car faisant référence à une population comme "Population (milliers)" de "pop", j'ai besoin qu'elles soient du même ordre de grandeur et je la renomme en "Population en sous nutrition (milliers)"


In [25]:
nutri["Valeur"] = nutri["Valeur"].replace("<0.1",0)
nutri["Valeur"] = pd.to_numeric(nutri["Valeur"])
nutri["Valeur"] = nutri["Valeur"] * 1000

In [26]:
nutri["Année"] = nutri["Année"].replace(["2012-2014","2013-2015","2014-2016","2015-2017","2016-2018","2017-2019"],["2013","2014","2015","2016","2017","2018"])
nutri.rename(columns = {"Zone" : "Pays"}, inplace = True)
nutri.rename(columns = {"Valeur" : "Population en sous nutrition (milliers)"}, inplace = True)
nutri["Année"] = nutri["Année"].astype("category")

In [27]:
nutri.head()

Pays Année  Population en sous nutrition (milliers)
0  Afghanistan  2013                                   8600.0
1  Afghanistan  2014                                   8800.0
2  Afghanistan  2015                                   8900.0
3  Afghanistan  2016                                   9700.0
4  Afghanistan  2017                                  10500.0

In [28]:
nutri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column                                   Non-Null Count  Dtype   
---  ------                                   --------------  -----   
 0   Pays                                     1218 non-null   object  
 1   Année                                    1218 non-null   category
 2   Population en sous nutrition (milliers)  624 non-null    float64 
dtypes: category(1), float64(1), object(1)
memory usage: 20.6+ KB


In [29]:
nutri.describe(include = "all")

Pays Année  Population en sous nutrition (milliers)
count          1218  1218                               624.000000
unique          203     6                                      NaN
top     Afghanistan  2013                                      NaN
freq              6   203                                      NaN
mean            NaN   NaN                              5103.846154
std             NaN   NaN                             19450.833220
min             NaN   NaN                                 0.000000
25%             NaN   NaN                               275.000000
50%             NaN   NaN                              1100.000000
75%             NaN   NaN                              3900.000000
max             NaN   NaN                            203800.000000

&nbsp;

## <font color=#2921CA> II - Marc

&nbsp;
    
**Pour l'année 2017 :**

- la proportion de personnes en état de sous-nutrition 
    

- le nombre théorique de personnes qui pourraient être nourries (calculable à partir de la disponibilité alimentaire mondiale)
    

- idem pour la disponibilité alimentaire des produits végétaux 
    

- l’utilisation de la disponibilité intérieure, en particulier la part qui est attribuée à l’alimentation animale, celle qui est perdue et celle qui est concrètement utilisée pour l'alimentation humaine (Julien avait trouvé un moyen de facilement calculer ces proportions)
    
&nbsp;
    
**Pour les demandes de Marc, j'ai besoin d'utiliser "dispo", "pop" et "nutri"**
    
**Comme il souhaite avoir des informations pour l'année 2017, je vais créer des nouveaux dataframes de "pop" et "nutri" avec les lignes correspondant à l'année 2017.**
    
**Malheuresement je n'ai que la disponibilité alimentaire pour l'année 2013, par conséquent les calculs provenant de "dispo" ne seront qu'une estimation théorique** 

In [30]:
pop_2017 = pop[pop["Année"] == 2017]
nutri_2017 = nutri[nutri["Année"] == "2017"]
pop_2017 = pop_2017.drop(columns = ["Année"])
nutri_2017 = nutri_2017.drop(columns = ["Année"])

&nbsp;

### <font color=#009F0C> A - Proportion de personnes en état de sous-nutrition
    
&nbsp;    
**Pour calculer le % de personnes en sous-nutrition, j'ai besoin de données dans "pop_2017" et dans "nutri_2017"**

In [31]:
nutri_2017.head()

Pays  Population en sous nutrition (milliers)
4      Afghanistan                                  10500.0
10  Afrique du Sud                                   3100.0
16         Albanie                                    100.0
22         Algérie                                   1300.0
28       Allemagne                                      NaN

In [32]:
pop_2017.head()

Pays  Population (milliers)
4      Afghanistan              36296.113
10  Afrique du Sud              57009.756
16         Albanie               2884.169
22         Algérie              41389.189
28       Allemagne              82658.409

**Je crée un dataframe issue d'une jointure externe entre les 2 avec "Pays" en clé commune**

**J'ajoute ensuite une nouvelle colonne calculant la proportion de personnes en sous-nutrition en utilisant "Population (milliers)" et "Population en sous nutrition (milliers)"**

In [33]:
pop_nutri_2017 = pd.merge(pop_2017, nutri_2017, on = "Pays", how = "outer")
pop_nutri_2017.head()

Pays  Population (milliers)  \
0     Afghanistan              36296.113   
1  Afrique du Sud              57009.756   
2         Albanie               2884.169   
3         Algérie              41389.189   
4       Allemagne              82658.409   

   Population en sous nutrition (milliers)  
0                                  10500.0  
1                                   3100.0  
2                                    100.0  
3                                   1300.0  
4                                      NaN

In [34]:
pop_nutri_2017.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 235
Data columns (total 3 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Pays                                     236 non-null    object 
 1   Population (milliers)                    236 non-null    float64
 2   Population en sous nutrition (milliers)  104 non-null    float64
dtypes: float64(2), object(1)
memory usage: 7.4+ KB


In [35]:
pop_nutri_2017.describe(include="all")

Pays  Population (milliers)  \
count           236           2.360000e+02   
unique          236                    NaN   
top     Afghanistan                    NaN   
freq              1                    NaN   
mean            NaN           3.198362e+04   
std             NaN           1.318949e+05   
min             NaN           7.930000e-01   
25%             NaN           3.803032e+02   
50%             NaN           5.203511e+03   
75%             NaN           1.930842e+04   
max             NaN           1.421022e+06   

        Population en sous nutrition (milliers)  
count                                104.000000  
unique                                      NaN  
top                                         NaN  
freq                                        NaN  
mean                                5150.961538  
std                                19121.019772  
min                                    0.000000  
25%                                  300.000000  
50%                                 1050.000000  
75%                                 3975.000000  
max                               190100.000000

In [36]:
pop_nutri_2017["Proportion sous-nutrition (%)"] = pop_nutri_2017["Population en sous nutrition (milliers)"]/pop_nutri_2017["Population (milliers)"]*100
pop_nutri_2017.head()

Pays  Population (milliers)  \
0     Afghanistan              36296.113   
1  Afrique du Sud              57009.756   
2         Albanie               2884.169   
3         Algérie              41389.189   
4       Allemagne              82658.409   

   Population en sous nutrition (milliers)  Proportion sous-nutrition (%)  
0                                  10500.0                      28.928718  
1                                   3100.0                       5.437666  
2                                    100.0                       3.467203  
3                                   1300.0                       3.140917  
4                                      NaN                            NaN

**A noter qu'il y a seulement 104 pays sur 236 avec une valeur non nulle dans "population en sous-nutrition"**

**Je vais créer un 2eme dataframe en gardant uniquement les lignes où la valeur de "population en sous-nutrition" n'est pas nulle**

**Je pourais ainsi comparer les calculs fait sur les 2 dataframes**

In [37]:
pop_nutri_2017.describe(include = 'all')

Pays  Population (milliers)  \
count           236           2.360000e+02   
unique          236                    NaN   
top     Afghanistan                    NaN   
freq              1                    NaN   
mean            NaN           3.198362e+04   
std             NaN           1.318949e+05   
min             NaN           7.930000e-01   
25%             NaN           3.803032e+02   
50%             NaN           5.203511e+03   
75%             NaN           1.930842e+04   
max             NaN           1.421022e+06   

        Population en sous nutrition (milliers)  Proportion sous-nutrition (%)  
count                                104.000000                     104.000000  
unique                                      NaN                            NaN  
top                                         NaN                            NaN  
freq                                        NaN                            NaN  
mean                                5150.961538                      11.409906  
std                                19121.019772                      11.452527  
min                                    0.000000                       0.000000  
25%                                  300.000000                       3.340897  
50%                                 1050.000000                       7.394353  
75%                                 3975.000000                      16.278717  
max                               190100.000000                      48.259182

In [38]:
pop_nutri_2017_nn = pop_nutri_2017.dropna()
pop_nutri_2017_nn.describe(include = 'all')

Pays  Population (milliers)  \
count           104           1.040000e+02   
unique          104                    NaN   
top     Afghanistan                    NaN   
freq              1                    NaN   
mean            NaN           4.021953e+04   
std             NaN           1.360991e+05   
min             NaN           7.145800e+01   
25%             NaN           2.763785e+03   
50%             NaN           1.074774e+04   
75%             NaN           3.157317e+04   
max             NaN           1.338677e+06   

        Population en sous nutrition (milliers)  Proportion sous-nutrition (%)  
count                                104.000000                     104.000000  
unique                                      NaN                            NaN  
top                                         NaN                            NaN  
freq                                        NaN                            NaN  
mean                                5150.961538                      11.409906  
std                                19121.019772                      11.452527  
min                                    0.000000                       0.000000  
25%                                  300.000000                       3.340897  
50%                                 1050.000000                       7.394353  
75%                                 3975.000000                      16.278717  
max                               190100.000000                      48.259182

**Pour chacun des dataframes, je créer une variable correspondant à la population totale et à la population totale en sous-nutrition** (la population sous-nutrition sera la même dans les 2 cas vu qu'il n'y a des valeurs nulles uniquement dans cette colonne)

**Avec ces variables je vais pouvoir calculer la proportion de population en sous-nutrition**

**Je check également l'ensemble des pays qui présentent des valeurs nulles dans "Population en sous nutrition (milliers)" et ceux qui n'ont pas une valeurs nulles pour avoir un bref aperçu de ces pays et voir si je peux en tirer quelque chose**   

In [39]:
pop_tot = pop_nutri_2017["Population (milliers)"].sum()
nutri_tot = pop_nutri_2017["Population en sous nutrition (milliers)"].sum()
prop_nutri = nutri_tot / pop_tot * 100

pop_tot_nn = pop_nutri_2017_nn["Population (milliers)"].sum()
prop_nutri_nn = nutri_tot / pop_tot_nn * 100

print("En 2017 : \n- La population totale était de", round(pop_tot/1000000,3),
      "Md \n- La population en sous-nutrition de", round(nutri_tot/1000,3),
      "M \n- La proportion de population en sous-nutrition était de", round(prop_nutri,1),"%",
      "\n \nSi on ne garde que les 104 pays où il y a une valeur renseignée pour la population en sous-nutrition, on obtient :",
      "\nUne population de", round(pop_tot_nn/1000000,3),"Md pour une proportion en sous-nutrition de", round(prop_nutri_nn,1),"%")

En 2017 : 
- La population totale était de 7.548 Md 
- La population en sous-nutrition de 535.7 M 
- La proportion de population en sous-nutrition était de 7.1 % 
 
Si on ne garde que les 104 pays où il y a une valeur renseignée pour la population en sous-nutrition, on obtient : 
Une population de 4.183 Md pour une proportion en sous-nutrition de 12.8 %


**Liste des pays dont la valeur de "Population en sous nutrition (milliers)" est nulle :**

In [40]:
pop_nutri_2017["Pays"].loc[pop_nutri_2017["Population en sous nutrition (milliers)"].isnull() == True].unique()

array(['Allemagne', 'Andorre', 'Anguilla', 'Antigua-et-Barbuda',
       'Antilles néerlandaises (ex)', 'Aruba', 'Australie', 'Autriche',
       'Azerbaïdjan', 'Bahamas', 'Bahreïn', 'Bélarus', 'Belgique',
       'Bermudes', 'Bhoutan', 'Bonaire, Saint-Eustache et Saba',
       'Bosnie-Herzégovine', 'Brésil', 'Brunéi Darussalam', 'Burundi',
       'Canada', 'Chine - RAS de Hong-Kong', 'Chine, continentale',
       'Comores', 'Croatie', 'Cuba', 'Curaçao', 'Danemark', 'Djibouti',
       'Érythrée', 'Espagne', 'Estonie', "États-Unis d'Amérique",
       'Fédération de Russie', 'Finlande', 'France', 'Gibraltar', 'Grèce',
       'Grenade', 'Groenland', 'Guadeloupe', 'Guam', 'Guinée',
       'Guinée équatoriale', 'Guinée-Bissau', 'Guyane française',
       'Hongrie', 'Île de Man', 'Îles Anglo-Normandes', 'Îles Caïmanes',
       'Îles Cook', 'Îles Falkland (Malvinas)', 'Îles Féroé',
       'Îles Mariannes du Nord', 'Îles Marshall',
       'Îles Turques-et-Caïques', 'Îles Vierges américaines',
   

**Liste des pays dont la valeur de "Population en sous nutrition (milliers)" n'est pas nulle :**

In [41]:
pop_nutri_2017_nn["Pays"].unique()

array(['Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Angola',
       'Arabie saoudite', 'Argentine', 'Arménie', 'Bangladesh', 'Barbade',
       'Belize', 'Bénin', 'Bolivie (État plurinational de)', 'Botswana',
       'Bulgarie', 'Burkina Faso', 'Cabo Verde', 'Cambodge', 'Cameroun',
       'Chili', 'Chine - RAS de Macao', 'Chine, Taiwan Province de',
       'Chypre', 'Colombie', 'Congo', 'Costa Rica', "Côte d'Ivoire",
       'Dominique', 'Égypte', 'El Salvador', 'Émirats arabes unis',
       'Équateur', 'Eswatini', 'Éthiopie', 'Fidji', 'Gabon', 'Gambie',
       'Géorgie', 'Ghana', 'Guatemala', 'Guyana', 'Haïti', 'Honduras',
       'Îles Salomon', 'Inde', 'Indonésie',
       "Iran (République islamique d')", 'Iraq', 'Jamaïque', 'Jordanie',
       'Kenya', 'Kirghizistan', 'Kiribati', 'Lesotho', 'Liban', 'Libéria',
       'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Malawi', 'Mali',
       'Maroc', 'Maurice', 'Mauritanie', 'Mexique', 'Mongolie',
       'Mozambique', 'Myanmar',

**A partir de ces 2 listes, je ne peux en tirer peu de choses, on remarquera que les pays occidentaux** (dont la population en sous-nutrition doit être très faible) **sont dans la liste où les valeurs sont nulles**

**Si on aurait pu espérer que ces valeurs manquantes soient proche de 0 et puissent être considérer égale à 0, on remarque que la liste est vaste et variée et qu'il y a propablement des valeurs manquanntes pour certains pays qui dans la réalité présentent une population en sous-nutrition non négligeable**

**De ce fait, on peut envisager que la population totale en sous-nutrition est supérieure à 535.7 M et donc que la proportion de population en sous-nutrition est plus élevée que les 7.1%** (on peut également supposer, vu les pays de cette liste, qu'elle reste néanmoins inférieure au 12.81%) 





&nbsp;

### <font color=#009F0C> B - Nombre théorique de personnes qui pourraient être nourries

&nbsp;
    
**Pour répondre à cette demande, je ne dispose que des données de disponibilité alimentaire pour l'année 2013 ce qui m'empêchera d'avoir un résultat fiable pour l'année 2017**
    
**Je commence dans un premier temps par grouper par pays "dispo". Cela me permet d'avoir la somme de "Disponibilité alimentaire (Kcal/personne/jour)" par pays**      

In [42]:
dispo.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

In [43]:
dispo_pays = dispo.groupby("Pays").sum()
dispo_pays.head()

Aliments pour animaux  Autres Utilisations  \
Pays                                                         
Afghanistan                     768.0                415.0   
Afrique du Sud                 5309.0                876.0   
Albanie                         660.0                174.0   
Algérie                        4352.0               1707.0   
Allemagne                     30209.0               7711.0   

                Disponibilité alimentaire (Kcal/personne/jour)  \
Pays                                                             
Afghanistan                                             2087.0   
Afrique du Sud                                          3020.0   
Albanie                                                 3188.0   
Algérie                                                 3293.0   
Allemagne                                               3503.0   

                Disponibilité alimentaire en quantité (kg/personne/an)  \
Pays                                                                     
Afghanistan                                                351.41        
Afrique du Sud                                             564.80        
Albanie                                                   1095.54        
Algérie                                                    809.13        
Allemagne                                                  957.52        

                Disponibilité de matière grasse en quantité (g/personne/jour)  \
Pays                                                                            
Afghanistan                                                 33.50               
Afrique du Sud                                              83.58               
Albanie                                                    106.48               
Algérie                                                     76.48               
Allemagne                                                  141.62               

                Disponibilité de protéines en quantité (g/personne/jour)  \
Pays                                                                       
Afghanistan                                                 58.26          
Afrique du Sud                                              85.33          
Albanie                                                    111.37          
Algérie                                                     91.92          
Allemagne                                                  101.39          

                Disponibilité intérieure  Exportations - Quantité  \
Pays                                                                
Afghanistan                      13515.0                    278.0   
Afrique du Sud                   61256.0                  11674.0   
Albanie                           4758.0                     94.0   
Algérie                          42630.0                    655.0   
Allemagne                       162275.0                  57431.0   

                Importations - Quantité  Nourriture  Pertes  Production  \
Pays                                                                      
Afghanistan                      2988.0     10735.0  1135.0     11171.0   
Afrique du Sud                   7517.0     29812.0  2193.0     63263.0   
Albanie                           933.0      3476.0   276.0      3964.0   
Algérie                         17403.0     31729.0  3753.0     26359.0   
Allemagne                       65353.0     79238.0  3781.0    154547.0   

                Semences  Traitement  Variation de stock  
Pays                                                      
Afghanistan        395.0        63.0              -368.0  
Afrique du Sud     253.0     22819.0              2153.0  
Albanie             55.0       113.0               -45.0  
Algérie            449.0       637.0              -479.0  
Allemagne         1551.0     39842.0              -192.0

**Pour obtenir la population potentiellement nourrie, je vais suivre les étapes suivantes :**

- Ayant la disponibilité alimentaire par personne, je fixe un indicateur moyen de 2250 Kcal/jour pour considérer qu'une personne est nourrie (moyenne de 2000/femme et 2500/homme)


- Avec cet indicateur, je vais pouvoir calcuer le taux de personnes nourries par pays


- Ce taux sera ensuite multiplié par la population pour me donner une population potentiellement nourrie par pays


- Puis la somme de ces populations potentiellement nourries me donnera une population globale

&nbsp;

**Le résultat me donnera le nombre pour l'année 2013. Pour le nombre théorique pour l'année 2017, il y aura 2 solutions :**

- **Cas 1 :** on considère que la disponibilité alimentaire totale par pays (Kcal/jour) est inchangée


- **Cas 2 :** on considère que la disponibilité alimentaire totale par pays (Kcal/jour) a évolué au même rythme que la population (c'est-à-dire que la disponibilité alimentaire en Kcal/pers/jour est inchangée)

&nbsp;

**Avant de commencer les manipulations sur les dataframes, je vais d'abord m'attarder sur ces 2 cas** 



&nbsp;

DA_tot (disponibilité alimentaire totale en kcal/jour) = DA_pers (disponibilité alimentaire en kcal/pers/jour) * Pop (Population)

Taux_pop_nour (Taux de population nourrie) = DA_pers / 2250

Pop_pot_nour (Population potentiellement nourrie) = Pop * Taux_pop_nour

&nbsp;

**Cas 1 : La disponibilité alimentaire totale par pays est inchangée**

&nbsp;

DA_tot_2013 = DA_tot_2017 = DA_pers_2013 * Pop_2013 = DA_pers_2017 * Pop_2017 

Taux_pop_nour_2013 = DA_pers_2013 / 2250 

Taux_pop_nour_2017 = DA_pers_2017 / 2250

Pop_pot_nour_2013 = Pop_2013 * Taux_pop_nour_2013

Pop_pot_nour_2017 = Pop_2017 * Taux_pop_nour_2017 

                  = Pop_2017 * (Da_pers_2017 / 2250) 
                  
                  = Pop_2017 * (DA_pers_2013 * Pop_2013 / Pop_2017) / 2250
                  
                  = Taux_pop_nour_2013 * Pop_2013
                  
                  = Pop_pot_nour_2013


**Pour le cas 1, si la disponibilité alimentaire totale est inchangée, alors la population potentiellement nourrie sera également inchangée**

&nbsp;

**Cas 2 : La disponibilité alimentaire par personne est inchangée**

&nbsp;

DA_pers_2013 = DA_pers_2017

Taux_pop_nour_2013 = DA_pers_2013 / 2250 = DA_pers_2017 / 2250 = Taux_pop_nour_2017 

Pop_pot_nour_2013 = Pop_2013 * Taux_pop_nour_2013

Pop_pot_nour_2017 = Pop_2017 * Taux_pop_nour_2017

                  = Pop_2017 / Pop_2013 * Pop_pot_nour_2013
                  

**Pour le cas 2, si la disponibilité alimentaire par personne est inchangée, alors la population potentiellement nourrie en 2017 sera celle de 2013 multipliée par (Popuplation de 2017 / Population de 2013)** 
                  
&nbsp;

**Maintenant, j'ai une vision plus claire des données qui vont m'être utiles pour répondre à la demande de Marc**

**Je vais devoir faire une jointure de "dispo_pays" avec "pop" pour les années 2013 et 2017**

**Je commence par créer un dataframe de "pop" avec les années 2013 et 2017**



In [44]:
pop_2013 = pop[pop["Année"]==2013]
pop_2013 = pop_2013.drop(columns = ["Année"])
pop_2013_2017 = pd.merge(pop_2013, pop_2017, on = 'Pays', how ='outer')
pop_2013_2017.rename(columns = {'Population (milliers)_x' : 'Population 2013', 'Population (milliers)_y' : 'Population 2017'}, inplace = True)
pop_2013_2017.head()

Pays  Population 2013  Population 2017
0     Afghanistan        32269.589        36296.113
1  Afrique du Sud        53687.121        57009.756
2         Albanie         2903.790         2884.169
3         Algérie        38140.133        41389.189
4       Allemagne        81174.367        82658.409

In [45]:
pop_dispo_pays_2013_2017 = pd.merge(dispo_pays, pop_2013_2017, on = "Pays", how = 'outer')
pop_dispo_pays_2013_2017 = pop_dispo_pays_2013_2017[['Pays','Disponibilité alimentaire (Kcal/personne/jour)','Population 2013','Population 2017']]
pop_dispo_pays_2013_2017.head()

Pays  Disponibilité alimentaire (Kcal/personne/jour)  \
0     Afghanistan                                          2087.0   
1  Afrique du Sud                                          3020.0   
2         Albanie                                          3188.0   
3         Algérie                                          3293.0   
4       Allemagne                                          3503.0   

   Population 2013  Population 2017  
0        32269.589        36296.113  
1        53687.121        57009.756  
2         2903.790         2884.169  
3        38140.133        41389.189  
4        81174.367        82658.409

**Je vais maintenant ajouter les colonnes pour le taux de population nourrie et la population potentiellement nourrie en 2013 ( = 2017 pour le cas 1) et en 2017 pour le cas 2**

**La somme de ces 2 dernières colonnes me donneront la population totale potentiellement nourrie**



In [46]:
pop_dispo_pays_2013_2017['Taux population nourri'] = pop_dispo_pays_2013_2017['Disponibilité alimentaire (Kcal/personne/jour)'] / 2250
pop_dispo_pays_2013_2017['Population potentiellement nourrie 2013'] = pop_dispo_pays_2013_2017['Taux population nourri'] * pop_dispo_pays_2013_2017['Population 2013']
pop_dispo_pays_2013_2017['Population potentiellement nourrie 2017 (cas 2)'] = pop_dispo_pays_2013_2017['Taux population nourri'] * pop_dispo_pays_2013_2017['Population 2017']
pop_dispo_pays_2013_2017.head()

Pays  Disponibilité alimentaire (Kcal/personne/jour)  \
0     Afghanistan                                          2087.0   
1  Afrique du Sud                                          3020.0   
2         Albanie                                          3188.0   
3         Algérie                                          3293.0   
4       Allemagne                                          3503.0   

   Population 2013  Population 2017  Taux population nourri  \
0        32269.589        36296.113                0.927556   
1        53687.121        57009.756                1.342222   
2         2903.790         2884.169                1.416889   
3        38140.133        41389.189                1.463556   
4        81174.367        82658.409                1.556889   

   Population potentiellement nourrie 2013  \
0                             29931.836552   
1                             72060.046853   
2                              4114.347787   
3                             55820.203542   
4                            126379.470045   

   Population potentiellement nourrie 2017 (cas 2)  
0                                     33666.661258  
1                                     76519.761387  
2                                      4086.547010  
3                                     60575.377501  
4                                    128689.958545

In [47]:
pt17 = pop_dispo_pays_2013_2017['Population 2017'].sum()
ptpn1 = pop_dispo_pays_2013_2017['Population potentiellement nourrie 2013'].sum()
ptpn2 = pop_dispo_pays_2013_2017['Population potentiellement nourrie 2017 (cas 2)'].sum()

print("Pour l'année 2017, on aurait une population théorique potentiellement nourrie de : \n \n- Cas 1 (Disponibilité alimentaire totale inchangée) :",
      round(ptpn1/1000000,3),"Md personnes, soit plus que la population mondiale qui était de \n", round(pt17/1000000,3),
      "Md en 2017 (soit un ratio de", round(ptpn1/pt17,2),
      "de la population mondiale pouvant potentiellement être nourrie) \n \n- Cas 2 (Disponibilité alimentaire par personne inchangée):",
      round(ptpn2/1000000,3),"Md personnes, également plus que la population mondiale \n(pour un ratio de",
      round(ptpn2/pt17,2),"de la population mondiale pouvant potentiellement être nourrie)")

Pour l'année 2017, on aurait une population théorique potentiellement nourrie de : 
 
- Cas 1 (Disponibilité alimentaire totale inchangée) : 8.909 Md personnes, soit plus que la population mondiale qui était de 
 7.548 Md en 2017 (soit un ratio de 1.18 de la population mondiale pouvant potentiellement être nourrie) 
 
- Cas 2 (Disponibilité alimentaire par personne inchangée): 9.297 Md personnes, également plus que la population mondiale 
(pour un ratio de 1.23 de la population mondiale pouvant potentiellement être nourrie)


&nbsp;

### <font color=#009F0C> C - Idem pour la disponibilité alimentaire des végétaux

&nbsp;
  
**Ici je vais réutiliser le procédé de la demande précédente en utilisant cette fois un dataframe où il n'y a que les lignes d'origine vegetale**    

In [48]:
dispo.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

In [49]:
dispo_veget = dispo[dispo["Origine"] == "vegetale"]
dispo_veget_pays = dispo_veget.groupby('Pays').sum()
dispo_veget_pays.head()

Aliments pour animaux  Autres Utilisations  \
Pays                                                         
Afghanistan                     645.0                415.0   
Afrique du Sud                 5122.0                761.0   
Albanie                         559.0                172.0   
Algérie                        4352.0               1706.0   
Allemagne                     28122.0               6842.0   

                Disponibilité alimentaire (Kcal/personne/jour)  \
Pays                                                             
Afghanistan                                             1871.0   
Afrique du Sud                                          2533.0   
Albanie                                                 2203.0   
Algérie                                                 2915.0   
Allemagne                                               2461.0   

                Disponibilité alimentaire en quantité (kg/personne/an)  \
Pays                                                                     
Afghanistan                                                271.49        
Afrique du Sud                                             425.17        
Albanie                                                    706.49        
Algérie                                                    632.35        
Allemagne                                                  568.82        

                Disponibilité de matière grasse en quantité (g/personne/jour)  \
Pays                                                                            
Afghanistan                                                 18.27               
Afrique du Sud                                              48.92               
Albanie                                                     38.76               
Algérie                                                     54.12               
Allemagne                                                   63.63               

                Disponibilité de protéines en quantité (g/personne/jour)  \
Pays                                                                       
Afghanistan                                                 46.05          
Afrique du Sud                                              48.94          
Albanie                                                     51.96          
Algérie                                                     66.94          
Allemagne                                                   39.90          

                Disponibilité intérieure  Exportations - Quantité  \
Pays                                                                
Afghanistan                      10884.0                    278.0   
Afrique du Sud                   53439.0                  10586.0   
Albanie                           3326.0                     84.0   
Algérie                          35510.0                    649.0   
Allemagne                       126866.0                  34454.0   

                Importations - Quantité  Nourriture  Pertes  Production  \
Pays                                                                      
Afghanistan                      2638.0      8293.0  1072.0      8891.0   
Afrique du Sud                   6468.0     22441.0  2110.0     55649.0   
Albanie                           846.0      2241.0   182.0      2609.0   
Algérie                         14672.0     24797.0  3587.0     21964.0   
Allemagne                       50642.0     47079.0  3717.0    110926.0   

                Semences  Traitement  Variation de stock  
Pays                                                      
Afghanistan        393.0        63.0              -368.0  
Afrique du Sud     186.0     22819.0              1912.0  
Albanie             55.0       113.0               -45.0  
Algérie            428.0       637.0              -479.0  
Allemagne         1475.0     39686.0              -247.0

**J'ai mon dataframe filtré sur vegetale (où le nombre de pays est resté identique après le filtrage)**

**Je vais pouvoir réitérer toutes les étapes de la B**

In [50]:
pop_dispo_veget_pays = pd.merge(dispo_veget_pays, pop_2013_2017, on = "Pays", how = 'outer')
pop_dispo_veget_pays = pop_dispo_veget_pays[['Pays','Disponibilité alimentaire (Kcal/personne/jour)','Population 2013','Population 2017']]
pop_dispo_veget_pays['Taux population nourri'] = pop_dispo_veget_pays['Disponibilité alimentaire (Kcal/personne/jour)'] / 2250
pop_dispo_veget_pays['Population potentiellement nourrie 2013'] = pop_dispo_veget_pays['Taux population nourri'] * pop_dispo_veget_pays['Population 2013']
pop_dispo_veget_pays['Population potentiellement nourrie 2017 (cas 2)'] = pop_dispo_veget_pays['Taux population nourri'] * pop_dispo_veget_pays['Population 2017']
pop_dispo_veget_pays.head()

Pays  Disponibilité alimentaire (Kcal/personne/jour)  \
0     Afghanistan                                          1871.0   
1  Afrique du Sud                                          2533.0   
2         Albanie                                          2203.0   
3         Algérie                                          2915.0   
4       Allemagne                                          2461.0   

   Population 2013  Population 2017  Taux population nourri  \
0        32269.589        36296.113                0.831556   
1        53687.121        57009.756                1.125778   
2         2903.790         2884.169                0.979111   
3        38140.133        41389.189                1.295556   
4        81174.367        82658.409                1.093778   

   Population potentiellement nourrie 2013  \
0                             26833.956008   
1                             60439.767775   
2                              2843.133053   
3                             49412.661198   
4                             88786.718750   

   Population potentiellement nourrie 2017 (cas 2)  
0                                     30182.234410  
1                                     64180.316421  
2                                      2823.921914  
3                                     53621.993749  
4                                     90409.930911

In [51]:
pt17v = pop_dispo_veget_pays['Population 2017'].sum()
ptpn1v = pop_dispo_veget_pays['Population potentiellement nourrie 2013'].sum()
ptpn2v = pop_dispo_veget_pays['Population potentiellement nourrie 2017 (cas 2)'].sum()

print("Pour l'année 2017, on aurait une population théorique potentiellement nourrie à partir des produits d'origine végétale de : \n \n- Cas 1 (Disponibilité alimentaire totale inchangée) :",
      round(ptpn1v/1000000,3),"Md personnes, soit quasiment la population totale de \n", round(pt17v/1000000,3),
      "Md en 2017 (ratio de", round(ptpn1v/pt17v,2),
      "de la population mondiale pouvant potentiellement être nourrie) \n \n- Cas 2 (Disponibilité alimentaire par personne inchangée):",
      round(ptpn2v/1000000,3),"Md personnes, donc un peu plus de la population totale \n(ratio de",
      round(ptpn2v/pt17v,2),"de la population mondiale pouvant potentiellement être nourrie)")

Pour l'année 2017, on aurait une population théorique potentiellement nourrie à partir des produits d'origine végétale de : 
 
- Cas 1 (Disponibilité alimentaire totale inchangée) : 7.336 Md personnes, soit quasiment la population totale de 
 7.548 Md en 2017 (ratio de 0.97 de la population mondiale pouvant potentiellement être nourrie) 
 
- Cas 2 (Disponibilité alimentaire par personne inchangée): 7.671 Md personnes, donc un peu plus de la population totale 
(ratio de 1.02 de la population mondiale pouvant potentiellement être nourrie)


**Avec seulement les produits d'origine vegetale, on s'aperçoit qu'ils sont suffisants (ou presque selon le cas) pour nourrir l'ensemble de la population mondiale**

**Je vais également regarder la proportion qu'ils constituent par rapport aux résultats de la B portant sur tout les produits**

In [52]:
print("- Cas 1 :", round(ptpn1/1000000,3),"Md personnes potentiellement nourrie (dont ",
      round(ptpn1v/1000000,3), "Md par les produits vétégaux, soit ", round(100*ptpn1v/ptpn1,2),
      "%) \n- Cas 2 :",round(ptpn2/1000000,3),"Md personnes potentiellement nourrie (dont ",
      round(ptpn2v/1000000,3), "Md par les produits vétégaux, soit ", round(100*ptpn2v/ptpn2,2), "%)")

- Cas 1 : 8.909 Md personnes potentiellement nourrie (dont  7.336 Md par les produits vétégaux, soit  82.35 %) 
- Cas 2 : 9.297 Md personnes potentiellement nourrie (dont  7.671 Md par les produits vétégaux, soit  82.51 %)


&nbsp;

### <font color=#009F0C> D - Utilisation de la disponibilité intérieure 
<font color=#009F0C>    (% d'alimentation animale, d'alimentation humaine et de pertes) 

&nbsp;
    
**Dans les notes des précédentes recherches de Julien, il indique qu'il existe un lien logique entre la disponibilité intérieure et les variables d'utilisiations/d'acquisitions de la disponibilité alimentaire**
    
**Ce lien serait formulé par une équation du type :**
    
**Disponibilité intérieure = Σ Ai = Σ Bi** (où Ai et Bi sont des variables d'utilisiations/d'acquisitions de la disponibilité alimentaire) 
    
**Dans un 1er temps je vais créer un dataframe à partir "dispo" en ne gardant que les colonnes de ces variables et de la disponibilité intérieure**
    
**Je vais ensuite chercher à retrouver le lien logique entre ces variables et la disponibilité intérieure**
    
**Puis je répondrai à la demande de marque sur la part d'utilisation de l'alimentation animale, de l'alimentation humaine et des pertes par rapport à la disponibilité intèrieure**
    





In [53]:
dispo.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

In [54]:
dispo_int = dispo[["Exportations - Quantité","Importations - Quantité","Nourriture","Pertes","Production","Semences","Traitement","Variation de stock","Aliments pour animaux","Autres Utilisations","Disponibilité intérieure"]]
dispo_int.head()

Exportations - Quantité  Importations - Quantité  Nourriture  Pertes  \
0                      NaN                      NaN        53.0     NaN   
1                      2.0                     40.0        39.0     2.0   
2                      NaN                      2.0         2.0     NaN   
3                      NaN                      0.0         0.0     NaN   
4                      NaN                     82.0        82.0     NaN   

   Production  Semences  Traitement  Variation de stock  \
0        53.0       NaN         NaN                 NaN   
1         3.0       NaN         NaN                 NaN   
2         NaN       NaN         NaN                 NaN   
3         NaN       NaN         NaN                 NaN   
4         NaN       NaN         NaN                 NaN   

   Aliments pour animaux  Autres Utilisations  Disponibilité intérieure  
0                    NaN                  NaN                      53.0  
1                    NaN                  NaN                      41.0  
2                    NaN                  NaN                       2.0  
3                    NaN                  NaN                       0.0  
4                    NaN                  NaN                      82.0

&nbsp;

#### <font color=#009F0C> 1) Lien logique entre disponibilité intérieure et les 10 variables de disponibilité alimentaire

&nbsp;
    
**On cherche : X = A = B**

Avec X = Disponibilité intérieure, A = Σ Ai et B = Σ Bi

**Pour cela on va procéder en plusieurs étapes et éliminer les variables au fur et à mesure**

&nbsp;

**Etape 1 :**

Je créer une copie de "dispo_int", sur laquelle je renomme "Disponibilité intérieure" en "X" et à laquelle je vais rajouter les colonnes "A" et "B" de mon équation

On va considérer que les NaN = 0 pour éviter certaines problématiques lors de nos calculs

In [55]:
di = dispo_int
di = di.rename(columns = {"Disponibilité intérieure" : "X"})
di = di.fillna(0)
di.head()

Exportations - Quantité  Importations - Quantité  Nourriture  Pertes  \
0                      0.0                      0.0        53.0     0.0   
1                      2.0                     40.0        39.0     2.0   
2                      0.0                      2.0         2.0     0.0   
3                      0.0                      0.0         0.0     0.0   
4                      0.0                     82.0        82.0     0.0   

   Production  Semences  Traitement  Variation de stock  \
0        53.0       0.0         0.0                 0.0   
1         3.0       0.0         0.0                 0.0   
2         0.0       0.0         0.0                 0.0   
3         0.0       0.0         0.0                 0.0   
4         0.0       0.0         0.0                 0.0   

   Aliments pour animaux  Autres Utilisations     X  
0                    0.0                  0.0  53.0  
1                    0.0                  0.0  41.0  
2                    0.0                  0.0   2.0  
3                    0.0                  0.0   0.0  
4                    0.0                  0.0  82.0

**Etape 2 :**

Maintenant que mon dataframe est prêt, je peux déjà observer plusieures choses :

ligne 0 : X = Nourriture = Production

ligne 2 et 4 : X = Nourriture = Importations

Ce qui ferait pour l'instant A = Nourriture et B = Production + Importations

Je créer les colonnes "A" et "B" à partir des colonnes de ces variables

Je supprime les colonnes de ces variables et utiliser la méthode .loc pour afficher les lignes où X != A et X != B 

*Remarque : je choisi d'utiliser "et" plutôt que "ou" sur les 2 conditions pour masquer plus de lignes et avoir plus de chance de trouver un lien avec les autres variable ("ou" étant le connecteur approprié si je voulais afficher toutes les lignes ne vérifiant pas l'équation X = A = B)*  

Puis je réitère le procédé pour compléter A et B avec les variables restantes


In [56]:
di["A"] = di["Nourriture"]
di["B"] = di["Production"] + di["Importations - Quantité"]
di = di.drop(columns = ["Nourriture","Production","Importations - Quantité"])
di.loc[(di["X"] != di["A"]) & (di["X"] != di["B"])].head()

Exportations - Quantité  Pertes  Semences  Traitement  Variation de stock  \
1                       2.0     2.0       0.0         0.0                 0.0   
7                       0.0   775.0     322.0         0.0              -350.0   
16                     69.0    17.0       0.0         0.0                 1.0   
30                     34.0   122.0       0.0         0.0                 0.0   
44                      7.0     4.0       0.0         0.0                 0.0   

    Aliments pour animaux  Autres Utilisations       X       A       B  
1                     0.0                  0.0    41.0    39.0    43.0  
7                     0.0                  0.0  5992.0  4895.0  6342.0  
16                    0.0                  0.0   240.0   223.0   308.0  
30                    0.0                  0.0  1007.0   885.0  1040.0  
44                    0.0                  0.0    72.0    68.0    79.0

**Etape 3 :**

ligne 1, 30 et 44 : On a des valeurs pour Exportations et Pertes

On peut déduire, déjà que Exportations sera en lien avec Importations dans B, et on aurait :

X = A + Pertes

X = B - Exportations

*Attention : pour la ligne 30, B - Exportations = 1040 - 34 = 1006 or X = 1007. On rencontre une différence de 1 unité sur le résulat attendu (on peut supposer qu'il y ait une petite marge d'erreur par rapport au degré de précision après la décimale de nos données, sans que cela impacte l'équation que l'on cherche)*

J'ajoute à "A" la colonne "Pertes" et je soustrait à "B" la colonne "Exportations - Quantité"

Je supprime ces colonnes et j'affiche les nouvelles lignes où X != A et X != B



In [57]:
di["A"] = di["A"] + di["Pertes"]
di["B"] = di["B"] - di["Exportations - Quantité"] 
di = di.drop(columns = ["Exportations - Quantité","Pertes"])
di.loc[(di["X"] != di["A"]) & (di["X"] != di["B"])].head()

Semences  Traitement  Variation de stock  Aliments pour animaux  \
7      322.0         0.0              -350.0                    0.0   
46       0.0         0.0                 0.0                    0.0   
72      31.0         0.0               450.0                   37.0   
85       0.0       133.0                34.0                    0.0   
87       0.0       112.0                 1.0                    0.0   

    Autres Utilisations       X       A       B  
7                   0.0  5992.0  5670.0  6342.0  
46                  0.0   513.0   514.0   514.0  
72                  0.0  3316.0  3248.0  2865.0  
85                  0.0   441.0   308.0   407.0  
87                  0.0   112.0     0.0   111.0

**Etape 4 :**

Ligne 87 : X = A + Traitement et X = B + Variation


In [58]:
di["A"] = di["A"] + di["Traitement"]
di["B"] = di["B"] + di["Variation de stock"]
di = di.drop(columns = ["Variation de stock","Traitement"])
di.loc[(di["X"] != di["A"]) & (di["X"] != di["B"])].head()

Semences  Aliments pour animaux  Autres Utilisations       X       A  \
46       0.0                    0.0                  0.0   513.0   514.0   
72      31.0                   37.0                  0.0  3316.0  3248.0   
89       3.0                    0.0                  0.0   590.0   587.0   
90       0.0                    0.0                 43.0    59.0    16.0   
91       5.0                    0.0                  0.0   105.0    99.0   

         B  
46   514.0  
72  3315.0  
89   589.0  
90    58.0  
91   104.0

**Etape 5**

Ligne 89 : X = A + Semences

Ligne 90 : X = A + Autres Utilisations

Ligne 72 : X = A + Semences + Aliments animaux


In [59]:
di["A"] = di["A"] + di["Semences"] + di["Aliments pour animaux"] + di["Autres Utilisations"]
di = di.drop(columns = ["Semences", "Aliments pour animaux","Autres Utilisations",])
di.loc[(di["X"] != di["A"]) & (di["X"] != di["B"])].head()

X        A        B
46     513.0    514.0    514.0
91     105.0    104.0    104.0
111  10480.0  10479.0  10481.0
117    497.0    498.0    498.0
123    158.0    157.0    157.0

**Etape 6 :**

Toutes les varibales ont trouvé une place dans l'équation X = A = B

On aurait :

- A = Nourriture + Pertes + Traitement + Semences + Aliments animaux + Autres utilisations

- B = Production + Importations - Exportations + Variation de stocks

Cependant on qu'il reste encore des lignes où X != B et X =! A

Lors de l'étape 3, j'avais noté à propos d'une ligne, une marge d'erreur d'une unité pour que X = B soit vérifié

A partir des 5 lignes ci-dessus, on observe également cette marge d'erreur d'une unité :

X = A ± 1 = B ± 1 

Je vais vérifier si cette équation est vraie pour l'ensemble des lignes en affichant toutes les lignes ne vérifiant pas cette équation

Pour cela je vais procéder en 2 parties, la 1ère pour X = A ± 1 et la 2ème pour X = B ± 1

In [60]:
di.loc[(di["X"] != di["A"]) & (di["X"] != di["A"] - 1) & (di["X"] != di["A"] + 1)]

X       A       B
107    3093.0  3097.0  3093.0
293    4542.0  4545.0  4541.0
343     -32.0     0.0   -32.0
350     425.0   427.0   424.0
379    1612.0  1639.0  1612.0
...       ...     ...     ...
15430  8728.0  8847.0  8729.0
15432   290.0   292.0   290.0
15480  4296.0  4300.0  4296.0
15500   279.0   282.0   279.0
15557    -2.0     0.0    -2.0

[300 rows x 3 columns]

In [61]:
di.loc[(di["X"] != di["B"]) & (di["X"] != di["B"] - 1) & (di["X"] != di["B"] + 1)]

X     A     B
3799  14.0  13.0  12.0
6758  69.0  68.0  67.0

**J'obtiens 300 lignes qui ne vérifie pas X = A ± 1 et 2 lignes qui ne vérifie pas X = B ± 1**

**Je vais regarder de plus près quelques exemples de lignes pour tenter de trouver une explication**

**Je repère par exemple, la ligne 343 avec X = -32 et A = 0 et la ligne 15430 avec X = 8728 et A = 8847 qui montrent une importante différence entre X et A**

**Je vais donc regarder les informations de ces lignes sur "dipo_int"**

In [62]:
dispo_int.iloc[343]

Exportations - Quantité     69.0
Importations - Quantité     37.0
Nourriture                   0.0
Pertes                       NaN
Production                   NaN
Semences                     NaN
Traitement                   NaN
Variation de stock           NaN
Aliments pour animaux        NaN
Autres Utilisations          NaN
Disponibilité intérieure   -32.0
Name: 343, dtype: float64

In [63]:
dispo_int.iloc[15430]

Exportations - Quantité      2289.0
Importations - Quantité       493.0
Nourriture                   8847.0
Pertes                          NaN
Production                  10525.0
Semences                        NaN
Traitement                      0.0
Variation de stock              0.0
Aliments pour animaux           NaN
Autres Utilisations             0.0
Disponibilité intérieure     8728.0
Name: 15430, dtype: float64

In [64]:
print(round(100 * 302 / len(di),2), "% des lignes ne vérifie pas X = A ± 1 ou X = B ± 1")

1.94 % des lignes ne vérifie pas X = A ± 1 ou X = B ± 1


J'observe :

- qu'il n'y a pas de solutions possibles pour vérifier X = A pour ces 2 lignes

- qu'il y a quelques valeurs manquantes

Lors de ma recherche du lien logique entre la disponibilité intérieure et les 10 variables, j'ai remplacé les valeurs manquantes par 0

Il se peut que ces données soient proches ou égales à 0 dans la réalité, mais également qu'elles aient une toute autre valeur, ce qui peut-être une explication de l'écart important entre X et A

Il y a 302 lignes, soit moins de 2%, pour lesquelles X = A ± 1 ou X = B ± 1 est faux. Cela représente un échantillon mineur du jeu de donnée et qui pourrait s'expliquer par le manque de données

Quand au ± 1 je vais considérer que les données ne sont pas assez précises au niveau des décimales d'où cette marge d'erreur

Je peux supposer que sans ces données manquantes et avec un meilleur degré de précision, X = A = B est vérifié pour :

- A = Nourriture + Pertes + Traitement + Semences + Aliments animaux + Autres utilisations


- B = Production + Importations - Exportations + Variation de stocks


#### <font color=#009F0C> 2) Part de la disponibilité intérieure (alimentation humaine, alimentation animale et pertes)

&nbsp;

**Pour trouver ces parts, je commence par créer un dataframe avec ces 4 variables tout en gardant les variables qualitatives sur lesquels j'effectuerai mes recherches**

In [65]:
dispo.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN

In [66]:
dispo_bis = dispo[["Pays","Produit","Origine","Disponibilité intérieure","Nourriture","Aliments pour animaux","Pertes",]]
dispo_bis.head()

Pays                Produit   Origine  Disponibilité intérieure  \
0  Afghanistan       Abats Comestible   animale                      53.0   
1  Afghanistan        Agrumes, Autres  vegetale                      41.0   
2  Afghanistan  Aliments pour enfants  vegetale                       2.0   
3  Afghanistan                 Ananas  vegetale                       0.0   
4  Afghanistan                Bananes  vegetale                      82.0   

   Nourriture  Aliments pour animaux  Pertes  
0        53.0                    NaN     NaN  
1        39.0                    NaN     2.0  
2         2.0                    NaN     NaN  
3         0.0                    NaN     NaN  
4        82.0                    NaN     NaN

**A partir des sommes des 4 variables quantitatives, je peux avoir le % global de "Nourriture", "Aliments pour animaux" et "Pertes" par rapport à "Disponibilité intérieure"**

In [67]:
sdi = dispo_bis["Disponibilité intérieure"].sum()
snou = dispo_bis["Nourriture"].sum()
sapa = dispo_bis["Aliments pour animaux"].sum()
sper = dispo_bis["Pertes"].sum()
print("Les parts de la disponibilité intérieure mondiale sont de : \n \n-",round(snou / sdi * 100,2),"% pour l'alimentation humaine \n \n-",
      round(sapa / sdi * 100,2),"% pour l'alimentation animale \n \n-",round(sper / sdi * 100,2), "% pour celle perdue")

Les parts de la disponibilité intérieure mondiale sont de : 
 
- 49.51 % pour l'alimentation humaine 
 
- 13.24 % pour l'alimentation animale 
 
- 4.61 % pour celle perdue


**Pour approfondir la recherche et avoir plus de détails sur les parts d'utilisiation de la disponibilité intérieure en fonction des pays, du type de produit et de l'origine du produit, je crée un dataframe pour chacune de ces variables avec un groupby**

**J'ajoute ensuite 3 colonnes représentant la part de l'alimentation humaine, de l'alimentation animale et des pertes, pour chacun des dataframes**

**Puis j'effectuerai un tri sur ces variables par ordre décroissant pour trouver d'éventuelles informations pertinentes**



In [68]:
dispo_bis_pays = dispo_bis.groupby("Pays").sum()
dispo_bis_produit = dispo_bis.groupby("Produit").sum()
dispo_bis_origine = dispo_bis.groupby("Origine").sum()

In [69]:
dispo_bis_pays["% Nourriture"] = round(dispo_bis_pays["Nourriture"]/dispo_bis_pays["Disponibilité intérieure"]*100,2)
dispo_bis_pays["% Aliments pour animaux"] = round(dispo_bis_pays["Aliments pour animaux"]/dispo_bis_pays["Disponibilité intérieure"]*100,2)
dispo_bis_pays["% Pertes"] = round(dispo_bis_pays["Pertes"]/dispo_bis_pays["Disponibilité intérieure"]*100,2)
dispo_bis_pays.head()

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Pays                                                                          
Afghanistan                      13515.0     10735.0                  768.0   
Afrique du Sud                   61256.0     29812.0                 5309.0   
Albanie                           4758.0      3476.0                  660.0   
Algérie                          42630.0     31729.0                 4352.0   
Allemagne                       162275.0     79238.0                30209.0   

                Pertes  % Nourriture  % Aliments pour animaux  % Pertes  
Pays                                                                     
Afghanistan     1135.0         79.43                     5.68      8.40  
Afrique du Sud  2193.0         48.67                     8.67      3.58  
Albanie          276.0         73.06                    13.87      5.80  
Algérie         3753.0         74.43                    10.21      8.80  
Allemagne       3781.0         48.83                    18.62      2.33

In [70]:
dispo_bis_produit["% Nourriture"] = round(dispo_bis_produit["Nourriture"]/dispo_bis_produit["Disponibilité intérieure"]*100,2)
dispo_bis_produit["% Aliments pour animaux"] = round(dispo_bis_produit["Aliments pour animaux"]/dispo_bis_produit["Disponibilité intérieure"]*100,2)
dispo_bis_produit["% Pertes"] = round(dispo_bis_produit["Pertes"]/dispo_bis_produit["Disponibilité intérieure"]*100,2)
dispo_bis_produit.head()

Disponibilité intérieure  Nourriture  \
Produit                                                        
Abats Comestible                         17587.0     15669.0   
Agrumes, Autres                          12176.0     11359.0   
Alcool, non Comestible                   21741.0         0.0   
Aliments pour enfants                       84.0       761.0   
Ananas                                   23282.0     20757.0   

                        Aliments pour animaux  Pertes  % Nourriture  \
Produit                                                               
Abats Comestible                       1009.0    73.0         89.09   
Agrumes, Autres                           0.0   810.0         93.29   
Alcool, non Comestible                    0.0     0.0          0.00   
Aliments pour enfants                     0.0     1.0        905.95   
Ananas                                    0.0  2745.0         89.15   

                        % Aliments pour animaux  % Pertes  
Produit                                                    
Abats Comestible                           5.74      0.42  
Agrumes, Autres                            0.00      6.65  
Alcool, non Comestible                     0.00      0.00  
Aliments pour enfants                      0.00      1.19  
Ananas                                     0.00     11.79

In [71]:
dispo_bis_origine["% Nourriture"] = round(dispo_bis_origine["Nourriture"]/dispo_bis_origine["Disponibilité intérieure"]*100,2)
dispo_bis_origine["% Aliments pour animaux"] = round(dispo_bis_origine["Aliments pour animaux"]/dispo_bis_origine["Disponibilité intérieure"]*100,2)
dispo_bis_origine["% Pertes"] = round(dispo_bis_origine["Pertes"]/dispo_bis_origine["Disponibilité intérieure"]*100,2)
dispo_bis_origine

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Origine                                                                 
animale                  1366750.0   1183716.0               107626.0   
vegetale                 8482244.0   3692542.0              1196619.0   

            Pertes  % Nourriture  % Aliments pour animaux  % Pertes  
Origine                                                              
animale    23930.0         86.61                     7.87      1.75  
vegetale  429768.0         43.53                    14.11      5.07

In [72]:
padi = round(100* dispo_bis_origine['Disponibilité intérieure'].iloc[0] / dispo_bis_origine['Disponibilité intérieure'].sum(),2)
pvdi = round(100* dispo_bis_origine['Disponibilité intérieure'].iloc[1] / dispo_bis_origine['Disponibilité intérieure'].sum(),2)
mnav = round(dispo_bis_origine['% Nourriture'].iloc[0] / dispo_bis_origine['% Nourriture'].iloc[1],1)
maav = dispo_bis_origine['% Aliments pour animaux'].iloc[0] / dispo_bis_origine['% Aliments pour animaux'].iloc[1]
mpav = dispo_bis_origine['% Pertes'].iloc[0] / dispo_bis_origine['% Pertes'].iloc[1]

In [73]:
print("On peut déjà noter, à partir de 'dispo_bis_origine' que la disponibilité intérieure est de", padi,
      "% d'origine animale \net", pvdi, "% d'origine vegetale. La part de la disponibilité intérieure : \n \n- pour l'alimentation des humains est",
      mnav, "fois + importante pour les produits d'origine animale que \nles produits d'origine végétale \n \n- pour l'alimentation des animaux est",
      round(1/maav,1), "fois - importante pour les produits d'origine animale que \nles produits d'origine végétale \n \n- perdue est",
      round(1/mpav,1), "fois - importante pour les produits d'origine animale que les produits d'origine végétale")
    

On peut déjà noter, à partir de 'dispo_bis_origine' que la disponibilité intérieure est de 13.88 % d'origine animale 
et 86.12 % d'origine vegetale. La part de la disponibilité intérieure : 
 
- pour l'alimentation des humains est 2.0 fois + importante pour les produits d'origine animale que 
les produits d'origine végétale 
 
- pour l'alimentation des animaux est 1.8 fois - importante pour les produits d'origine animale que 
les produits d'origine végétale 
 
- perdue est 2.9 fois - importante pour les produits d'origine animale que les produits d'origine végétale


In [74]:
dispo_bis_pays.sort_values(["% Nourriture"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  \
Pays                                                             
Chine - RAS de Macao                         383.0       368.0   
Timor-Leste                                  447.0       419.0   
Yémen                                       9782.0      9162.0   
Lesotho                                      966.0       899.0   
Rwanda                                     10054.0      9273.0   
Mauritanie                                  2142.0      1947.0   
Chine - RAS de Hong-Kong                    6424.0      5778.0   
Botswana                                    1253.0      1113.0   
Brunéi Darussalam                            294.0       261.0   
Bermudes                                      59.0        51.0   

                          Aliments pour animaux  Pertes  % Nourriture  \
Pays                                                                    
Chine - RAS de Macao                        0.0     1.0         96.08   
Timor-Leste                                 9.0    14.0         93.74   
Yémen                                     210.0   269.0         93.66   
Lesotho                                     1.0    51.0         93.06   
Rwanda                                      0.0   435.0         92.23   
Mauritanie                                 89.0    75.0         90.90   
Chine - RAS de Hong-Kong                  100.0   216.0         89.94   
Botswana                                   24.0    51.0         88.83   
Brunéi Darussalam                           9.0     4.0         88.78   
Bermudes                                    1.0     0.0         86.44   

                          % Aliments pour animaux  % Pertes  
Pays                                                         
Chine - RAS de Macao                         0.00      0.26  
Timor-Leste                                  2.01      3.13  
Yémen                                        2.15      2.75  
Lesotho                                      0.10      5.28  
Rwanda                                       0.00      4.33  
Mauritanie                                   4.15      3.50  
Chine - RAS de Hong-Kong                     1.56      3.36  
Botswana                                     1.92      4.07  
Brunéi Darussalam                            3.06      1.36  
Bermudes                                     1.69      0.00

In [75]:
dispo_bis_pays.sort_values(["% Aliments pour animaux"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Pays                                                                           
Danemark                          19749.0      5795.0                 7835.0   
Arabie saoudite                   31274.0     17956.0                11841.0   
Bélarus                           27522.0      8721.0                10204.0   
Tadjikistan                        7617.0      4271.0                 2775.0   
Irlande                           10738.0      5320.0                 3758.0   
Turkménistan                       7404.0      3541.0                 2486.0   
Canada                            79562.0     33945.0                26137.0   
Ukraine                          113924.0     39790.0                37085.0   
Serbie                            18156.0      7118.0                 5581.0   
Chypre                             1319.0       728.0                  394.0   

                 Pertes  % Nourriture  % Aliments pour animaux  % Pertes  
Pays                                                                      
Danemark          582.0         29.34                    39.67      2.95  
Arabie saoudite  1040.0         57.42                    37.86      3.33  
Bélarus           571.0         31.69                    37.08      2.07  
Tadjikistan       266.0         56.07                    36.43      3.49  
Irlande           236.0         49.54                    35.00      2.20  
Turkménistan      272.0         47.83                    33.58      3.67  
Canada           2118.0         42.66                    32.85      2.66  
Ukraine          4138.0         34.93                    32.55      3.63  
Serbie            707.0         39.20                    30.74      3.89  
Chypre             50.0         55.19                    29.87      3.79

In [76]:
dispo_bis_pays.sort_values(["% Pertes"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Pays                                                                        
Sierra Leone                    6570.0      3070.0                  901.0   
Ghana                          38998.0     22482.0                 4878.0   
Cameroun                       26222.0     15259.0                 2166.0   
Angola                         32029.0     15059.0                 9259.0   
Dominique                        141.0        68.0                   20.0   
Guinée                          8404.0      5711.0                  648.0   
Malawi                         19877.0      8607.0                 4009.0   
Togo                            4095.0      3186.0                  151.0   
Bulgarie                        9458.0      5111.0                 1055.0   
Bénin                          11966.0      6236.0                 2004.0   

              Pertes  % Nourriture  % Aliments pour animaux  % Pertes  
Pays                                                                   
Sierra Leone  2191.0         46.73                    13.71     33.35  
Ghana         7442.0         57.65                    12.51     19.08  
Cameroun      3981.0         58.19                     8.26     15.18  
Angola        4799.0         47.02                    28.91     14.98  
Dominique       20.0         48.23                    14.18     14.18  
Guinée        1074.0         67.96                     7.71     12.78  
Malawi        2428.0         43.30                    20.17     12.22  
Togo           476.0         77.80                     3.69     11.62  
Bulgarie      1090.0         54.04                    11.15     11.52  
Bénin         1357.0         52.11                    16.75     11.34

- La Chine est le pays où la part de la disponibilité intérieure utilisée pour l'alimentation des humains est la plus élevée avec 96%


- Le Danemark est le pays où la part de la disponibilité intérieure utilisée pour l'alimentation des animaux est la plus élevée avec 40% 


- La Sierra Leone est le pays où la part de la disponibilité intérieure perdue est la plus élevée avec 33%. On notera que l'écart est très important avec le 2e pays de ce classment (le Ghana avec 19%). Je remarque également que le top 10 est consitué de 8 pays africains, on notera la Dominique en 5e position et la Bulgarie en 9e position

In [77]:
dispo_bis_produit.sort_values(["% Nourriture"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  \
Produit                                                        
Aliments pour enfants                       84.0       761.0   
Viande, Autre                             6809.0      6823.0   
Bière                                   187348.0    187051.0   
Thé                                       5930.0      5910.0   
Viande de Suides                        112547.0    112100.0   
Mollusques, Autres                       17622.0     17498.0   
Viande de Bovins                         65715.0     65216.0   
Viande d'Ovins/Caprins                   13501.0     13389.0   
Café                                      8176.0      8101.0   
Beurre, Ghee                              9819.0      9718.0   

                        Aliments pour animaux  Pertes  % Nourriture  \
Produit                                                               
Aliments pour enfants                     0.0     1.0        905.95   
Viande, Autre                            57.0    13.0        100.21   
Bière                                     0.0    43.0         99.84   
Thé                                       0.0   115.0         99.66   
Viande de Suides                          0.0   275.0         99.60   
Mollusques, Autres                       38.0     0.0         99.30   
Viande de Bovins                          9.0   463.0         99.24   
Viande d'Ovins/Caprins                   18.0    33.0         99.17   
Café                                      0.0   114.0         99.08   
Beurre, Ghee                              6.0    91.0         98.97   

                        % Aliments pour animaux  % Pertes  
Produit                                                    
Aliments pour enfants                      0.00      1.19  
Viande, Autre                              0.84      0.19  
Bière                                      0.00      0.02  
Thé                                        0.00      1.94  
Viande de Suides                           0.00      0.24  
Mollusques, Autres                         0.22      0.00  
Viande de Bovins                           0.01      0.70  
Viande d'Ovins/Caprins                     0.13      0.24  
Café                                       0.00      1.39  
Beurre, Ghee                               0.06      0.93

In [78]:
dispo_bis_produit.sort_values(["% Aliments pour animaux"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  \
Produit                                                     
Avoine                                23407.0      3903.0   
Céréales, Autres                      27485.0      5324.0   
Orge                                 140439.0      6794.0   
Maïs                                 955799.0    125184.0   
Seigle                                16567.0      5502.0   
Huiles de Poissons                      828.0        67.0   
Poissons Pelagiques                   41024.0     21687.0   
Sorgho                                58237.0     24153.0   
Patates douces                        99442.0     57058.0   
Manioc                               256664.0    100637.0   

                     Aliments pour animaux   Pertes  % Nourriture  \
Produit                                                             
Avoine                             16251.0    514.0         16.67   
Céréales, Autres                   19035.0    785.0         19.37   
Orge                               92658.0   4628.0          4.84   
Maïs                              546116.0  40701.0         13.10   
Seigle                              8099.0    562.0         33.21   
Huiles de Poissons                   387.0      0.0          8.09   
Poissons Pelagiques                18817.0      0.0         52.86   
Sorgho                             24808.0   2746.0         41.47   
Patates douces                     35259.0   6431.0         57.38   
Manioc                             87056.0  30537.0         39.21   

                     % Aliments pour animaux  % Pertes  
Produit                                                 
Avoine                                 69.43      2.20  
Céréales, Autres                       69.26      2.86  
Orge                                   65.98      3.30  
Maïs                                   57.14      4.26  
Seigle                                 48.89      3.39  
Huiles de Poissons                     46.74      0.00  
Poissons Pelagiques                    45.87      0.00  
Sorgho                                 42.60      4.72  
Patates douces                         35.46      6.47  
Manioc                                 33.92     11.90

In [79]:
dispo_bis_produit.sort_values(["% Pertes"], ascending = False).head(10)

Disponibilité intérieure  Nourriture  \
Produit                                                   
Racines nda                         19423.0     14066.0   
Bananes                            103992.0     85954.0   
Manioc                             256664.0    100637.0   
Ananas                              23282.0     20757.0   
Bananes plantains                   29233.0     22863.0   
Ignames                             62665.0     32511.0   
Pommes de Terre                    377504.0    239077.0   
Citrons & Limes                     15769.0     14190.0   
Fruits, Autres                     205956.0    185475.0   
Tomates                            159452.0    144080.0   

                   Aliments pour animaux   Pertes  % Nourriture  \
Produit                                                           
Racines nda                        792.0   3262.0         72.42   
Bananes                            871.0  15295.0         82.65   
Manioc                           87056.0  30537.0         39.21   
Ananas                               0.0   2745.0         89.15   
Bananes plantains                  562.0   3222.0         78.21   
Ignames                           4913.0   6764.0         51.88   
Pommes de Terre                  47273.0  35458.0         63.33   
Citrons & Limes                      0.0   1416.0         89.99   
Fruits, Autres                      61.0  18045.0         90.06   
Tomates                           1870.0  13419.0         90.36   

                   % Aliments pour animaux  % Pertes  
Produit                                               
Racines nda                           4.08     16.79  
Bananes                               0.84     14.71  
Manioc                               33.92     11.90  
Ananas                                0.00     11.79  
Bananes plantains                     1.92     11.02  
Ignames                               7.84     10.79  
Pommes de Terre                      12.52      9.39  
Citrons & Limes                       0.00      8.98  
Fruits, Autres                        0.03      8.76  
Tomates                               1.17      8.42

- Pour l'alimentation des humains, on remarque un cas particulier avec + de 900% de part dans l'alimentation des humains pour les aliments pour enfants. Les viandes, ainsi que les boissons spécifiques à l'homme constituent le haut du classement avec une part > 99%


- Pour l'alimentation des animaux, on remarque un top 5 constitué avec des produits de type céréales, avec un podium ('Avoine', 'Céréales, Autres', 'Orge') compris entre 65% et 70% de part de la disponibilité intérieure


- Pour les pertes, on remarque que le haut du classement est constitué de plantes, de fruits et de légumes, notamment 'Racines nda' avec le taux de pertes le plus élevé (17%) 

&nbsp;


## <font color=#2921CA> III - Mélanie

&nbsp;
    
- Pays pour lesquels la proportion de personnes sous-alimentées est la plus forte en 2017
    

- Pays qui ont le plus bénéficié d’aide depuis 2013
    

- Pays ayant le plus/le moins de disponibilité/habitant
    

- Toutes les infos que tu trouverais utiles pour mettre en relief les pays qui semblent être le plus en difficulté, au niveau alimentaire

&nbsp;

### <font color=#009F0C> A - Pays avec les propotions de sous-nutrition les plus fortes en 2017

&nbsp;

**Je peux réutiliser 'pop_nutri_2017' qui nous indiquait déjà la proportion de sous-nutrition par pays, j'aurais juste à faire un tri décroissant sur la colonne 'Proportion sous-nutrition (%)'**

In [80]:
pop_nutri_2017.head()

Pays  Population (milliers)  \
0     Afghanistan              36296.113   
1  Afrique du Sud              57009.756   
2         Albanie               2884.169   
3         Algérie              41389.189   
4       Allemagne              82658.409   

   Population en sous nutrition (milliers)  Proportion sous-nutrition (%)  
0                                  10500.0                      28.928718  
1                                   3100.0                       5.437666  
2                                    100.0                       3.467203  
3                                   1300.0                       3.140917  
4                                      NaN                            NaN

In [81]:
prop_nutri_2017 = pop_nutri_2017[["Pays","Proportion sous-nutrition (%)"]]
prop_nutri_2017.sort_values("Proportion sous-nutrition (%)", ascending = False).head(10)

Pays  Proportion sous-nutrition (%)
87                                        Haïti                      48.259182
181  République populaire démocratique de Corée                      47.188685
128                                  Madagascar                      41.062924
122                                     Libéria                      38.279742
119                                     Lesotho                      38.249438
216                                       Tchad                      37.957606
186                                      Rwanda                      35.055619
145                                  Mozambique                      32.810898
219                                 Timor-Leste                      32.173531
0                                   Afghanistan                      28.928718

**Les pays qui souffrent le plus de sous-nutrition sont essentiellement en Asie ou en Afrique, mais c'est Haiti dans les caraïbes (connu pour le grand nombre de catastrophes naturelles importantes subies) qui est tête de ce classement avec 48% de la population en état de sous-nutrition**

&nbsp;

### <font color=#009F0C> B - Pays ayant bénéficiés le plus d'aides depuis 2013
    
&nbsp;
    
**Je vais avoir besoin de "aide" et je vais regarder les différentes années qui figurent dedans**      

In [82]:
aide.head()

Pays Année              Produit  Quantité aide alimetaire (tonnes)
0  Afghanistan  2013  Autres non-céréales                                682
1  Afghanistan  2014  Autres non-céréales                                335
2  Afghanistan  2013         Blé et Farin                              39224
3  Afghanistan  2014         Blé et Farin                              15160
4  Afghanistan  2013             Céréales                              40504

In [83]:
aide["Année"].unique()

[2013, 2014, 2015, 2016]
Categories (4, int64): [2013, 2014, 2015, 2016]

**Les années de "aide" vont de 2013 à 2016, c'est parfait j'ai juste à calculer la somme de la quantité d'aide alimentaire reçue par pays, puis de faire un tri décroissant**

In [84]:
aide_pays = aide.groupby("Pays").sum()
aide_pays.sort_values("Quantité aide alimetaire (tonnes)", ascending = False).head(10)

Quantité aide alimetaire (tonnes)
Pays                                                               
République arabe syrienne                                   1858943
Éthiopie                                                    1381294
Yémen                                                       1206484
Soudan du Sud                                                695248
Soudan                                                       669784
Kenya                                                        552836
Bangladesh                                                   348188
Somalie                                                      292678
République démocratique du Congo                             288502
Niger                                                        276344

**Depuis 2013, la Syrie est le pays qui a bénéficié le plus d'aide alimentaire (en guerre depuis 2011), la suite du classment est constitué de 8 pays africains et du Bangladesh**

&nbsp;

### <font color=#009F0C> C - Pays ayant le plus/le moins de disponibilité/habitant
    
&nbsp;   
    
**Je peux réutiliser "dispo_pays" à partir duquel je vais créer un nouveau dataframe avec les disponibilité alimentaire**   

In [85]:
dispo_pays.head()

Aliments pour animaux  Autres Utilisations  \
Pays                                                         
Afghanistan                     768.0                415.0   
Afrique du Sud                 5309.0                876.0   
Albanie                         660.0                174.0   
Algérie                        4352.0               1707.0   
Allemagne                     30209.0               7711.0   

                Disponibilité alimentaire (Kcal/personne/jour)  \
Pays                                                             
Afghanistan                                             2087.0   
Afrique du Sud                                          3020.0   
Albanie                                                 3188.0   
Algérie                                                 3293.0   
Allemagne                                               3503.0   

                Disponibilité alimentaire en quantité (kg/personne/an)  \
Pays                                                                     
Afghanistan                                                351.41        
Afrique du Sud                                             564.80        
Albanie                                                   1095.54        
Algérie                                                    809.13        
Allemagne                                                  957.52        

                Disponibilité de matière grasse en quantité (g/personne/jour)  \
Pays                                                                            
Afghanistan                                                 33.50               
Afrique du Sud                                              83.58               
Albanie                                                    106.48               
Algérie                                                     76.48               
Allemagne                                                  141.62               

                Disponibilité de protéines en quantité (g/personne/jour)  \
Pays                                                                       
Afghanistan                                                 58.26          
Afrique du Sud                                              85.33          
Albanie                                                    111.37          
Algérie                                                     91.92          
Allemagne                                                  101.39          

                Disponibilité intérieure  Exportations - Quantité  \
Pays                                                                
Afghanistan                      13515.0                    278.0   
Afrique du Sud                   61256.0                  11674.0   
Albanie                           4758.0                     94.0   
Algérie                          42630.0                    655.0   
Allemagne                       162275.0                  57431.0   

                Importations - Quantité  Nourriture  Pertes  Production  \
Pays                                                                      
Afghanistan                      2988.0     10735.0  1135.0     11171.0   
Afrique du Sud                   7517.0     29812.0  2193.0     63263.0   
Albanie                           933.0      3476.0   276.0      3964.0   
Algérie                         17403.0     31729.0  3753.0     26359.0   
Allemagne                       65353.0     79238.0  3781.0    154547.0   

                Semences  Traitement  Variation de stock  
Pays                                                      
Afghanistan        395.0        63.0              -368.0  
Afrique du Sud     253.0     22819.0              2153.0  
Albanie             55.0       113.0               -45.0  
Algérie            449.0       637.0              -479.0  
Allemagne         1551.0     39842.0              -192.0

In [86]:
dispo_alim_pays = dispo_pays[["Disponibilité alimentaire (Kcal/personne/jour)","Disponibilité alimentaire en quantité (kg/personne/an)","Disponibilité de matière grasse en quantité (g/personne/jour)","Disponibilité de protéines en quantité (g/personne/jour)"]]
dispo_alim_pays.head()

Disponibilité alimentaire (Kcal/personne/jour)  \
Pays                                                             
Afghanistan                                             2087.0   
Afrique du Sud                                          3020.0   
Albanie                                                 3188.0   
Algérie                                                 3293.0   
Allemagne                                               3503.0   

                Disponibilité alimentaire en quantité (kg/personne/an)  \
Pays                                                                     
Afghanistan                                                351.41        
Afrique du Sud                                             564.80        
Albanie                                                   1095.54        
Algérie                                                    809.13        
Allemagne                                                  957.52        

                Disponibilité de matière grasse en quantité (g/personne/jour)  \
Pays                                                                            
Afghanistan                                                 33.50               
Afrique du Sud                                              83.58               
Albanie                                                    106.48               
Algérie                                                     76.48               
Allemagne                                                  141.62               

                Disponibilité de protéines en quantité (g/personne/jour)  
Pays                                                                      
Afghanistan                                                 58.26         
Afrique du Sud                                              85.33         
Albanie                                                    111.37         
Algérie                                                     91.92         
Allemagne                                                  101.39

In [87]:
print(f"TOP 10 ayant le plus de disponibilité alimentaire/habitant :\n \n{dispo_alim_pays['Disponibilité alimentaire (Kcal/personne/jour)'].sort_values(ascending = False).head(10)},\n \n\
TOP 10 ayant le moins disponibilité alimentaire/habitant :\n \n{dispo_alim_pays['Disponibilité alimentaire (Kcal/personne/jour)'].sort_values().head(10)}")                                                                                                                        

TOP 10 ayant le plus de disponibilité alimentaire/habitant :
 
Pays
Autriche                 3770.0
Belgique                 3737.0
Turquie                  3708.0
États-Unis d'Amérique    3682.0
Israël                   3610.0
Irlande                  3602.0
Italie                   3578.0
Luxembourg               3540.0
Égypte                   3518.0
Allemagne                3503.0
Name: Disponibilité alimentaire (Kcal/personne/jour), dtype: float64,
 
TOP 10 ayant le moins disponibilité alimentaire/habitant :
 
Pays
République centrafricaine                     1879.0
Zambie                                        1924.0
Madagascar                                    2056.0
Afghanistan                                   2087.0
Haïti                                         2089.0
République populaire démocratique de Corée    2093.0
Tchad                                         2109.0
Zimbabwe                                      2113.0
Ouganda                                       2126

In [88]:
print(f"TOP 10 ayant le plus de disponibilité alimentaire en quantité/habitant :\n \n{dispo_alim_pays['Disponibilité alimentaire en quantité (kg/personne/an)'].sort_values(ascending = False).head(10)},\n \n\
TOP 10 ayant le moins disponibilité alimentaire en quantité/habitant :\n \n{dispo_alim_pays['Disponibilité alimentaire en quantité (kg/personne/an)'].sort_values().head(10)}") 

TOP 10 ayant le plus de disponibilité alimentaire en quantité/habitant :
 
Pays
Monténégro    1210.41
Luxembourg    1150.66
Irlande       1150.15
Albanie       1095.54
Finlande      1093.77
Grèce         1070.90
Pays-Bas      1069.22
Autriche      1069.20
Lituanie      1050.07
Danemark      1031.04
Name: Disponibilité alimentaire en quantité (kg/personne/an), dtype: float64,
 
TOP 10 ayant le moins disponibilité alimentaire en quantité/habitant :
 
Pays
Tchad            319.45
Zimbabwe         336.59
Zambie           350.12
Afghanistan      351.41
Éthiopie         354.55
Guinée-Bissau    358.48
Bangladesh       364.54
Timor-Leste      369.10
Yémen            375.41
Sénégal          376.72
Name: Disponibilité alimentaire en quantité (kg/personne/an), dtype: float64


- Les pays qui possèdent le plus de disponibilité alimentaire/habitant (en calorie réélle ou en quantité) sont en grande majorité issus de l'Europe, les autres étant les Etats-Unis, Israël et l'Egypte


- Les pays qui possèdent le moins de disponibilité alimentaire/habitant (en calorie réélle ou en quantité) sont en grande partie issus de l'Afrique et de l'Asie, avec Haiti comme execption. On remarque d'ailleurs que nombreux des pays de ces 2 listes figuraient dans les classements, vue précédemment, sur la proportion de sous-nutrition en 2017 et sur les pays ayant bénéficié le plus d'aides depuis 2013


**Je vais récupérer les classements vue dans les parties précédentes pour voir quels sont les pays commun à chacun des classements en utilisant des jointures internes**

In [89]:
t10_sous_nutri = prop_nutri_2017.sort_values("Proportion sous-nutrition (%)", ascending = False).head(10)
t10_aide = aide_pays.sort_values("Quantité aide alimetaire (tonnes)", ascending = False).head(10)
t10_dispo_kg = dispo_alim_pays['Disponibilité alimentaire en quantité (kg/personne/an)'].sort_values().head(10)
t10_dispo_kcal = dispo_alim_pays['Disponibilité alimentaire (Kcal/personne/jour)'].sort_values().head(10)

In [90]:
t10_sous_nutri

Pays  Proportion sous-nutrition (%)
87                                        Haïti                      48.259182
181  République populaire démocratique de Corée                      47.188685
128                                  Madagascar                      41.062924
122                                     Libéria                      38.279742
119                                     Lesotho                      38.249438
216                                       Tchad                      37.957606
186                                      Rwanda                      35.055619
145                                  Mozambique                      32.810898
219                                 Timor-Leste                      32.173531
0                                   Afghanistan                      28.928718

In [91]:
t10_aide

Quantité aide alimetaire (tonnes)
Pays                                                               
République arabe syrienne                                   1858943
Éthiopie                                                    1381294
Yémen                                                       1206484
Soudan du Sud                                                695248
Soudan                                                       669784
Kenya                                                        552836
Bangladesh                                                   348188
Somalie                                                      292678
République démocratique du Congo                             288502
Niger                                                        276344

In [92]:
t10_dispo_kcal

Pays
République centrafricaine                     1879.0
Zambie                                        1924.0
Madagascar                                    2056.0
Afghanistan                                   2087.0
Haïti                                         2089.0
République populaire démocratique de Corée    2093.0
Tchad                                         2109.0
Zimbabwe                                      2113.0
Ouganda                                       2126.0
Timor-Leste                                   2129.0
Name: Disponibilité alimentaire (Kcal/personne/jour), dtype: float64

In [93]:
t10_dispo_kg

Pays
Tchad            319.45
Zimbabwe         336.59
Zambie           350.12
Afghanistan      351.41
Éthiopie         354.55
Guinée-Bissau    358.48
Bangladesh       364.54
Timor-Leste      369.10
Yémen            375.41
Sénégal          376.72
Name: Disponibilité alimentaire en quantité (kg/personne/an), dtype: float64

In [94]:
t10_nutri_kcal = pd.merge(t10_sous_nutri, t10_dispo_kcal, on = 'Pays', how = 'inner')
t10_nutri_kcal

Pays  Proportion sous-nutrition (%)  \
0                                       Haïti                      48.259182   
1  République populaire démocratique de Corée                      47.188685   
2                                  Madagascar                      41.062924   
3                                       Tchad                      37.957606   
4                                 Timor-Leste                      32.173531   
5                                 Afghanistan                      28.928718   

   Disponibilité alimentaire (Kcal/personne/jour)  
0                                          2089.0  
1                                          2093.0  
2                                          2056.0  
3                                          2109.0  
4                                          2129.0  
5                                          2087.0

In [95]:
t10_nutri_kg = pd.merge(t10_sous_nutri, t10_dispo_kg, on = 'Pays', how = 'inner')
t10_nutri_kg

Pays  Proportion sous-nutrition (%)  \
0        Tchad                      37.957606   
1  Timor-Leste                      32.173531   
2  Afghanistan                      28.928718   

   Disponibilité alimentaire en quantité (kg/personne/an)  
0                                             319.45       
1                                             369.10       
2                                             351.41

In [96]:
t10_aide_kcal = pd.merge(t10_aide, t10_dispo_kcal, on = 'Pays', how = 'inner')
t10_aide_kcal

Empty DataFrame
Columns: [Quantité aide alimetaire (tonnes), Disponibilité alimentaire (Kcal/personne/jour)]
Index: []

In [97]:
t10_aide_kg = pd.merge(t10_aide, t10_dispo_kg, on = 'Pays', how = 'inner')
t10_aide_kg

Quantité aide alimetaire (tonnes)  \
Pays                                            
Éthiopie                              1381294   
Yémen                                 1206484   
Bangladesh                             348188   

            Disponibilité alimentaire en quantité (kg/personne/an)  
Pays                                                                
Éthiopie                                               354.55       
Yémen                                                  375.41       
Bangladesh                                             364.54

- Pour le Top 10 des pays affichant la proportion de population en sous-nutrition la plus élevée en 2017, on retrouve 6 pays dans le Top 10 des pays ayant le moins de disponibilité alimentaire (en Kcal) en 2013 dont 3 également dans le Top 10 des pays ayant le moins de disponibilité alimentaire en quantité (en kg) en 2013


- Pour le Top 10 des pays ayant bénéficié le plus d'aide depuis 2013, il n'y pas de pays commun avec le Top 10 des pays ayant le moins de disponibilité alimentaire (en Kcal) en 2013, par contre il y a 3 pays qui sont dans le Top 10 des pays ayant le moins de disponibilité alimentaire en quantité (en kg)


    
    

&nbsp;

##  <font color=#2921CA> IV - Julien

&nbsp;
    
- Lien logique entre l’ensemble des 10 variables exprimées en milliers de tonnes sur
les utilisations de la disponibilité intérieure
    

- L’utilisation des céréales, notamment la répartition entre l’alimentation humaine et l’alimentation
pour animaux

    
- Utilisation du manioc par la Thaïlande aux égards de la proportion de personnes en sous-nutrition
    
&nbsp;   

### <font color=#009F0C> A - Lien logique entre disponibilité intérieure et les variables d'utilisations/moyens acquisition

&nbsp;
    
**J'ai déjà étudié la question lors de la partie II - D**

&nbsp;    
    
*Pour rappel, il fallait trouver une équation du type Disponibilité intérieure = Σ Ai = Σ Bi* 
     
*(où Ai et Bi appartiennent à l’ensemble des 10 variables exprimées en milliers de tonnes sur les utilisations de la disponibilité intérieure)*
    
J'avais trouvé Disponibilité intérieure = Nourriture + Pertes + Traitement + Semences + Aliments animaux + Autres utilisations
    
                              = Production + Importations - Exportations + Variation de stocks 
    
    

&nbsp;
        
### <font color=#009F0C> B - Utilisation des céréales
  <font color=#009F0C>  (Répartition alimentation humaine et alimentation animale)

&nbsp;

**Je commenece par chercher la liste des produits de type céréales, celle-ci est disponible sur le site de FAOSTAT sur lequel je télécharge un fichier de bilan alimentaire pour les produits appartenant au groupe céréales pour l'année 2013**


In [98]:
céréales = pd.read_csv("C:\\Users\\narab\\OneDrive\\Documents\\OpenClassRooms\\Projet 4\\Nouveau Dossier\\céréales_2013.csv")

In [99]:
céréales.head()

Code Domaine                                            Domaine  \
0         FBSH  Bilans Alimentaires (-2013, ancienne méthodolo...   
1         FBSH  Bilans Alimentaires (-2013, ancienne méthodolo...   
2         FBSH  Bilans Alimentaires (-2013, ancienne méthodolo...   
3         FBSH  Bilans Alimentaires (-2013, ancienne méthodolo...   
4         FBSH  Bilans Alimentaires (-2013, ancienne méthodolo...   

   Code zone (M49)         Zone  Code Élément                   Élément  \
0                4  Afghanistan          5511                Production   
1                4  Afghanistan          5611   Importations - Quantité   
2                4  Afghanistan          5072        Variation de stock   
3                4  Afghanistan          5301  Disponibilité intérieure   
4                4  Afghanistan          5527                  Semences   

  Code Produit (CPC)          Produit  Code année  Année               Unité  \
0              S2511  Blé et produits        2013   2013  Milliers de tonnes   
1              S2511  Blé et produits        2013   2013  Milliers de tonnes   
2              S2511  Blé et produits        2013   2013  Milliers de tonnes   
3              S2511  Blé et produits        2013   2013  Milliers de tonnes   
4              S2511  Blé et produits        2013   2013  Milliers de tonnes   

   Valeur Symbole Description du Symbole  
0  5169.0       I         Valeur imputée  
1  1173.0       I         Valeur imputée  
2  -350.0       I         Valeur imputée  
3  5992.0       I         Valeur imputée  
4   322.0       I         Valeur imputée

In [100]:
céréales["Produit"].unique()

array(['Blé et produits', 'Riz (Eq Blanchi)', 'Orge et produits',
       'Maïs et produits', 'Millet et produits', 'Céréales, Autres',
       'Seigle et produits', 'Avoine', 'Sorgho et produits'], dtype=object)

**Voici la liste de tout les produits de type céréales**

**Je crée une liste rassemblant tout ces produits en vérifant leur orthographe "dispo"**

**Je crée un dataframe à partir de "dispo" en utilisant la liste comme filtre de la colonne "Produit"**

In [101]:
dispo["Produit"].unique()

array(['Abats Comestible', 'Agrumes, Autres', 'Aliments pour enfants',
       'Ananas', 'Bananes', 'Beurre, Ghee', 'Bière', 'Blé',
       'Boissons Alcooliques', 'Café', 'Coco (Incl Coprah)', 'Crème',
       'Céréales, Autres', 'Dattes', 'Edulcorants Autres',
       'Feve de Cacao', 'Fruits, Autres', 'Graines de coton',
       'Graines de tournesol', 'Graisses Animales Crue',
       'Huil Plantes Oleif Autr', 'Huile Graines de Coton',
       "Huile d'Arachide", "Huile d'Olive", 'Huile de Colza&Moutarde',
       'Huile de Palme', 'Huile de Soja', 'Huile de Sésame',
       'Huile de Tournesol', 'Lait - Excl Beurre', 'Légumes, Autres',
       'Légumineuses Autres', 'Maïs', 'Miel', 'Millet', 'Miscellanees',
       'Noix', 'Oeufs', 'Olives', 'Oranges, Mandarines', 'Orge',
       'Plantes Oleiferes, Autre', 'Poissons Eau Douce', 'Poivre',
       'Pommes', 'Pommes de Terre', 'Raisin', 'Riz (Eq Blanchi)',
       'Sucre Eq Brut', 'Sucre, betterave', 'Sucre, canne', 'Sésame',
       'Thé', 'Toma

**Liste des produits de "céréales" et leur équivalent dans "dispo" :** 

- 'Avoine' : 'Avoine'
- 'Blé et produits' : 'Blé'
- 'Céréales, Autres' : 'Céréales, Autres'
- 'Maïs et produits' : 'Maïs'
- 'Millet et produits' : 'Millet'
- 'Orge et produits' : 'Orge'
- 'Riz (Eq Blanchi)' : 'Riz (Eq Blanchi)'
- 'Seigle et produits' : 'Seigle'
- 'Sorgho et produits' : 'Sorgho'


In [102]:
liste_céréales = ['Avoine', 'Blé', 'Céréales, Autres', 'Maïs', 'Millet', 'Orge', 'Riz (Eq Blanchi)', 'Seigle', 'Sorgho']
dispo_céréales = dispo.loc[dispo["Produit"].isin(liste_céréales)]
dispo_céréales.head()

Pays           Produit   Origine  Aliments pour animaux  \
7   Afghanistan               Blé  vegetale                    NaN   
12  Afghanistan  Céréales, Autres  vegetale                    NaN   
32  Afghanistan              Maïs  vegetale                  200.0   
34  Afghanistan            Millet  vegetale                    NaN   
40  Afghanistan              Orge  vegetale                  360.0   

    Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
7                   NaN                                          1369.0   
12                  NaN                                             0.0   
32                  NaN                                            21.0   
34                  NaN                                             3.0   
40                  NaN                                            26.0   

    Disponibilité alimentaire en quantité (kg/personne/an)  \
7                                              160.23        
12                                               0.00        
32                                               2.50        
34                                               0.40        
40                                               2.92        

    Disponibilité de matière grasse en quantité (g/personne/jour)  \
7                                                4.69               
12                                               0.00               
32                                               0.30               
34                                               0.02               
40                                               0.24               

    Disponibilité de protéines en quantité (g/personne/jour)  \
7                                               36.91          
12                                               0.00          
32                                               0.56          
34                                               0.08          
40                                               0.79          

    Disponibilité intérieure  Exportations - Quantité  \
7                     5992.0                      NaN   
12                       0.0                      NaN   
32                     313.0                      0.0   
34                      13.0                      NaN   
40                     524.0                      NaN   

    Importations - Quantité  Nourriture  Pertes  Production  Semences  \
7                    1173.0      4895.0   775.0      5169.0     322.0   
12                      0.0         0.0     NaN         NaN       NaN   
32                      1.0        76.0    31.0       312.0       5.0   
34                      NaN        12.0     1.0        13.0       0.0   
40                     10.0        89.0    52.0       514.0      22.0   

    Traitement  Variation de stock  
7          NaN              -350.0  
12         NaN                 NaN  
32         NaN                 NaN  
34         NaN                 NaN  
40         NaN                 0.0

In [103]:
dispo_céréales.describe(include='all')

Pays Produit   Origine  Aliments pour animaux  Autres Utilisations  \
count     1497    1497      1497            1071.000000           527.000000   
unique     174       9         1                    NaN                  NaN   
top     Koweït     Blé  vegetale                    NaN                  NaN   
freq         9     174      1497                    NaN                  NaN   
mean       NaN     NaN       NaN             815.625584           445.516129   
std        NaN     NaN       NaN            6352.933738          6172.049887   
min        NaN     NaN       NaN               0.000000             0.000000   
25%        NaN     NaN       NaN               0.000000             0.000000   
50%        NaN     NaN       NaN              10.000000             2.000000   
75%        NaN     NaN       NaN             199.000000            23.500000   
max        NaN     NaN       NaN          150000.000000        137023.000000   

        Disponibilité alimentaire (Kcal/personne/jour)  \
count                                      1270.000000   
unique                                             NaN   
top                                                NaN   
freq                                               NaN   
mean                                        153.638583   
std                                         284.726619   
min                                         -21.000000   
25%                                           1.000000   
50%                                          14.000000   
75%                                         148.500000   
max                                        1711.000000   

        Disponibilité alimentaire en quantité (kg/personne/an)  \
count                                         1259.000000        
unique                                                NaN        
top                                                   NaN        
freq                                                  NaN        
mean                                            18.596966        
std                                             34.465613        
min                                             -1.930000        
25%                                              0.150000        
50%                                              2.040000        
75%                                             17.530000        
max                                            222.400000        

        Disponibilité de matière grasse en quantité (g/personne/jour)  \
count                                         1142.000000               
unique                                                NaN               
top                                                   NaN               
freq                                                  NaN               
mean                                             0.933923               
std                                              1.891326               
min                                             -0.030000               
25%                                              0.010000               
50%                                              0.110000               
75%                                              0.830000               
max                                             14.840000               

        Disponibilité de protéines en quantité (g/personne/jour)  \
count                                         1218.000000          
unique                                                NaN          
top                                                   NaN          
freq                                                  NaN          
mean                                             4.129647          
std                                              7.741356          
min                                             -0.370000          
25%                                              0.040000          
50%                                              0.470000          
75

In [104]:
dispo_céréales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1497 entries, 7 to 15593
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Pays                                                           1497 non-null   object 
 1   Produit                                                        1497 non-null   object 
 2   Origine                                                        1497 non-null   object 
 3   Aliments pour animaux                                          1071 non-null   float64
 4   Autres Utilisations                                            527 non-null    float64
 5   Disponibilité alimentaire (Kcal/personne/jour)                 1270 non-null   float64
 6   Disponibilité alimentaire en quantité (kg/personne/an)         1259 non-null   float64
 7   Disponibilité de matière grasse en quantité (g/personne/jou

**Je vais garder uniquement les variables qualitatives 'Pays' et 'Produit' et les variables quantitatives ''Disponibilité intérieure','Nourriture', 'Aliments pour animaux'**

**Je crée des variables correspondant aux sommes de mes variables quantitatives pour voir leur répartition**

In [105]:
dispo_céréales_hum_ani = dispo_céréales[['Pays', 'Produit', 'Disponibilité intérieure','Nourriture', 'Aliments pour animaux']]
dispo_céréales_hum_ani.head()

Pays           Produit  Disponibilité intérieure  Nourriture  \
7   Afghanistan               Blé                    5992.0      4895.0   
12  Afghanistan  Céréales, Autres                       0.0         0.0   
32  Afghanistan              Maïs                     313.0        76.0   
34  Afghanistan            Millet                      13.0        12.0   
40  Afghanistan              Orge                     524.0        89.0   

    Aliments pour animaux  
7                     NaN  
12                    NaN  
32                  200.0  
34                    NaN  
40                  360.0

In [106]:
di_sum = dispo_céréales_hum_ani['Disponibilité intérieure'].sum()
hu_sum = dispo_céréales_hum_ani['Nourriture'].sum()
an_sum = dispo_céréales_hum_ani['Aliments pour animaux'].sum()

In [107]:
print("L'utilisation globale des céréales représente une utilisation de", round(hu_sum/di_sum*100,2), "% pour l'alimentation humaine et \nde", round(an_sum/di_sum*100,2), "% pour l'alimentation des animaux") 

L'utilisation globale des céréales représente une utilisation de 42.75 % pour l'alimentation humaine et 
de 36.29 % pour l'alimentation des animaux


**Je crée 2 nouveaux dataframes, l'un où je groupe par pays, l'autre où je groupe par produit**

**J'ajoute à ces dataframes des colonnes de la proportion d'utilisation en alimentation humaine et en alimentation animale**

**J'effectue un tri décroissant en fonction de ces proportions sur les 2 dataframes**

In [108]:
dcha_produit = dispo_céréales_hum_ani.groupby("Produit").sum()
dcha_pays = dispo_céréales_hum_ani.groupby("Pays").sum()
dcha_produit["% Utilisation humains"]=dcha_produit["Nourriture"]/dcha_produit["Disponibilité intérieure"]*100
dcha_produit["% Utilisation animaux"]=dcha_produit["Aliments pour animaux"]/dcha_produit["Disponibilité intérieure"]*100
dcha_pays["% Utilisation humains"]=dcha_pays["Nourriture"]/dcha_pays["Disponibilité intérieure"]*100
dcha_pays["% Utilisation animaux"]=dcha_pays["Aliments pour animaux"]/dcha_pays["Disponibilité intérieure"]*100

In [109]:
dcha_produit.sort_values("% Utilisation animaux", ascending = False)

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Produit                                                                         
Avoine                             23407.0      3903.0                16251.0   
Céréales, Autres                   27485.0      5324.0                19035.0   
Orge                              140439.0      6794.0                92658.0   
Maïs                              955799.0    125184.0               546116.0   
Seigle                             16567.0      5502.0                 8099.0   
Sorgho                             58237.0     24153.0                24808.0   
Blé                               679498.0    457824.0               129668.0   
Millet                             29911.0     23040.0                 3306.0   
Riz (Eq Blanchi)                  475656.0    377286.0                33594.0   

                  % Utilisation humains  % Utilisation animaux  
Produit                                                         
Avoine                        16.674499              69.427949  
Céréales, Autres              19.370566              69.255958  
Orge                           4.837688              65.977399  
Maïs                          13.097314              57.137118  
Seigle                        33.210599              48.886340  
Sorgho                        41.473634              42.598348  
Blé                           67.376799              19.082911  
Millet                        77.028518              11.052790  
Riz (Eq Blanchi)              79.319088               7.062667

In [110]:
dcha_produit.sort_values("% Utilisation humains", ascending = False)

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Produit                                                                         
Riz (Eq Blanchi)                  475656.0    377286.0                33594.0   
Millet                             29911.0     23040.0                 3306.0   
Blé                               679498.0    457824.0               129668.0   
Sorgho                             58237.0     24153.0                24808.0   
Seigle                             16567.0      5502.0                 8099.0   
Céréales, Autres                   27485.0      5324.0                19035.0   
Avoine                             23407.0      3903.0                16251.0   
Maïs                              955799.0    125184.0               546116.0   
Orge                              140439.0      6794.0                92658.0   

                  % Utilisation humains  % Utilisation animaux  
Produit                                                         
Riz (Eq Blanchi)              79.319088               7.062667  
Millet                        77.028518              11.052790  
Blé                           67.376799              19.082911  
Sorgho                        41.473634              42.598348  
Seigle                        33.210599              48.886340  
Céréales, Autres              19.370566              69.255958  
Avoine                        16.674499              69.427949  
Maïs                          13.097314              57.137118  
Orge                           4.837688              65.977399

In [111]:
dcha_pays.sort_values("% Utilisation animaux", ascending = False).head(10)

Disponibilité intérieure  Nourriture  Aliments pour animaux  \
Pays                                                                           
Danemark                           8073.0       737.0                 6649.0   
Irlande                            3742.0       584.0                 2861.0   
Espagne                           33495.0      4971.0                24926.0   
Canada                            32769.0      4200.0                23905.0   
Croatie                            2816.0       520.0                 1990.0   
Arabie saoudite                   16595.0      4439.0                11680.0   
Serbie                             7069.0      1277.0                 4956.0   
Bélarus                            7760.0      1040.0                 5356.0   
Chypre                              450.0       106.0                  310.0   
Pays-Bas                          10995.0      1489.0                 7566.0   

                 % Utilisation humains  % Utilisation animaux  
Pays                                                           
Danemark                      9.129196              82.360956  
Irlande                      15.606627              76.456440  
Espagne                      14.841021              74.417077  
Canada                       12.816992              72.950044  
Croatie                      18.465909              70.667614  
Arabie saoudite              26.749021              70.382645  
Serbie                       18.064790              70.108926  
Bélarus                      13.402062              69.020619  
Chypre                       23.555556              68.888889  
Pays-Bas                     13.542519              68.813097

In [112]:
dcha_pays.sort_values("% Utilisation humains").head(10)

Disponibilité intérieure  Nourriture  \
Pays                                                          
Danemark                                 8073.0       737.0   
États-Unis d'Amérique                  343006.0     33810.0   
Canada                                  32769.0      4200.0   
Bélarus                                  7760.0      1040.0   
Pays-Bas                                10995.0      1489.0   
Espagne                                 33495.0      4971.0   
Irlande                                  3742.0       584.0   
Hongrie                                  7085.0      1143.0   
Australie                               12608.0      2048.0   
Belgique                                 7987.0      1378.0   

                       Aliments pour animaux  % Utilisation humains  \
Pays                                                                  
Danemark                              6649.0               9.129196   
États-Unis d'Amérique               140096.0               9.856970   
Canada                               23905.0              12.816992   
Bélarus                               5356.0              13.402062   
Pays-Bas                              7566.0              13.542519   
Espagne                              24926.0              14.841021   
Irlande                               2861.0              15.606627   
Hongrie                               4273.0              16.132675   
Australie                             7936.0              16.243655   
Belgique                              3279.0              17.253036   

                       % Utilisation animaux  
Pays                                          
Danemark                           82.360956  
États-Unis d'Amérique              40.843600  
Canada                             72.950044  
Bélarus                            69.020619  
Pays-Bas                           68.813097  
Espagne                            74.417077  
Irlande                            76.456440  
Hongrie                            60.310515  
Australie                          62.944162  
Belgique                           41.054213

- Il y a des céréales plutôt utilisées pour l'alimentation animale : Avoine, Orge, Autres (à plus de 65%)


- Il y a des céréales plutôt utilisées pour l'alimentation humaine : Riz, Millet, Blé (à plus de 67%)


- On retrouve le Danemark (cf II - D) en tête du classement avec 82 % d'utilisation des céréales pour l'alimentation des animaux, également beaucoup d'autres pays européens, le Canada et l'Arabie Saoudite dans le top 10


- On retrouve 6 de ces pays dans ceux qui utilisent le moins les céréales pour l'alimentation humaine, les 4 nouveaux étant les Etats-Unis (2e), la Hongrie (8e), l'Australie (9e) et la Belgique (10e)


&nbsp;

### <font color=#009F0C> C - Utilisation du manioc en Thailande

<font color=#009F0C> (Aux égards de la proportion de personnes en sous-nutrition - Exportation par rapport à la production)
    
&nbsp;    
    




In [113]:
nutri.head()

Pays Année  Population en sous nutrition (milliers)
0  Afghanistan  2013                                   8600.0
1  Afghanistan  2014                                   8800.0
2  Afghanistan  2015                                   8900.0
3  Afghanistan  2016                                   9700.0
4  Afghanistan  2017                                  10500.0

In [114]:
pop_2013.head()

Pays  Population (milliers)
0      Afghanistan              32269.589
6   Afrique du Sud              53687.121
12         Albanie               2903.790
18         Algérie              38140.133
24       Allemagne              81174.367

In [115]:
nutri_2013 = nutri.loc[nutri['Année'] == '2013']
nutri_2013 = nutri_2013.drop(columns = ['Année'])
pop_nutri_2013 = pd.merge(pop_2013,nutri_2013, on = 'Pays', how = 'outer')
pop_nutri_2013["Proportion sous-nutrition (%)"] = pop_nutri_2013["Population en sous nutrition (milliers)"]/pop_nutri_2013["Population (milliers)"]*100
pop_nutri_2013.head()

Pays  Population (milliers)  \
0     Afghanistan              32269.589   
1  Afrique du Sud              53687.121   
2         Albanie               2903.790   
3         Algérie              38140.133   
4       Allemagne              81174.367   

   Population en sous nutrition (milliers)  Proportion sous-nutrition (%)  
0                                   8600.0                      26.650479  
1                                   2200.0                       4.097817  
2                                    100.0                       3.443775  
3                                   1300.0                       3.408483  
4                                      NaN                            NaN

In [116]:
dispo_pop_nutri_2013 = pd.merge(dispo, pop_nutri_2013, on = 'Pays', how='outer')
dispo_pop_nutri_2013.head()

Pays                Produit   Origine  Aliments pour animaux  \
0  Afghanistan       Abats Comestible   animale                    NaN   
1  Afghanistan        Agrumes, Autres  vegetale                    NaN   
2  Afghanistan  Aliments pour enfants  vegetale                    NaN   
3  Afghanistan                 Ananas  vegetale                    NaN   
4  Afghanistan                Bananes  vegetale                    NaN   

   Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                  NaN                                             5.0   
1                  NaN                                             1.0   
2                  NaN                                             1.0   
3                  NaN                                             0.0   
4                  NaN                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                               1.72        
1                                               1.29        
2                                               0.06        
3                                               0.00        
4                                               2.70        

   Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                               0.20               
1                                               0.01               
2                                               0.01               
3                                                NaN               
4                                               0.02               

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  ...  Importations - Quantité  Nourriture  Pertes  \
0                      53.0  ...                      NaN        53.0     NaN   
1                      41.0  ...                     40.0        39.0     2.0   
2                       2.0  ...                      2.0         2.0     NaN   
3                       0.0  ...                      0.0         0.0     NaN   
4                      82.0  ...                     82.0        82.0     NaN   

   Production  Semences  Traitement  Variation de stock  \
0        53.0       NaN         NaN                 NaN   
1         3.0       NaN         NaN                 NaN   
2         NaN       NaN         NaN                 NaN   
3         NaN       NaN         NaN                 NaN   
4         NaN       NaN         NaN                 NaN   

   Population (milliers)  Population en sous nutrition (milliers)  \
0              32269.589                                   8600.0   
1              32269.589                                   8600.0   
2              32269.589                                   8600.0   
3              32269.589                                   8600.0   
4              32269.589                                   8600.0   

   Proportion sous-nutrition (%)  
0                      26.650479  
1                      26.650479  
2                      26.650479  
3                      26.650479  
4                      26.650479  

[5 rows x 21 columns]

In [117]:
thai_manioc = dispo_pop_nutri_2013.loc[(dispo_pop_nutri_2013['Pays'] == 'Thaïlande') & (dispo_pop_nutri_2013['Produit'] == 'Manioc')]
thai_manioc

Pays Produit   Origine  Aliments pour animaux  \
13809  Thaïlande  Manioc  vegetale                 1800.0   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13809               2081.0                                            40.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13809                                               13.0        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13809                                               0.05               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13809                                               0.14          

       Disponibilité intérieure  ...  Importations - Quantité  Nourriture  \
13809                    6264.0  ...                   1250.0       871.0   

       Pertes  Production  Semences  Traitement  Variation de stock  \
13809  1511.0     30228.0       NaN         0.0                 0.0   

       Population (milliers)  Population en sous nutrition (milliers)  \
13809              68144.518                                   6200.0   

       Proportion sous-nutrition (%)  
13809                       9.098311  

[1 rows x 21 columns]

In [118]:
tmp = thai_manioc['Production'].sum()
tme = thai_manioc['Exportations - Quantité'].sum()
tpsn = thai_manioc['Proportion sous-nutrition (%)'].sum()
print ("En 2013, la Thaïlande a produit", round(tmp), "tonnes de manioc et en a exporté", round(tme),
       "tonnes (soit", round((tme / tmp).sum()*100,2), "% de la production)",
       "\n \nLa proportion de population en sous-nutrition était de", round(tpsn,2), "%")

En 2013, la Thaïlande a produit 30228 tonnes de manioc et en a exporté 25214 tonnes (soit 83.41 % de la production) 
 
La proportion de population en sous-nutrition était de 9.1 %


In [119]:
manioc_prodexport = dispo_pop_nutri_2013[["Pays","Proportion sous-nutrition (%)","Production","Exportations - Quantité"]].loc[dispo_pop_nutri_2013["Produit"] == "Manioc"]
manioc_prodexport["% Export/Production"] = manioc_prodexport["Exportations - Quantité"] / manioc_prodexport["Production"] * 100
manioc_prodexport.head()

Pays  Proportion sous-nutrition (%)  Production  \
110  Afrique du Sud                       4.097817         NaN   
203         Albanie                       3.443775         NaN   
295         Algérie                       3.408483         NaN   
390       Allemagne                            NaN         NaN   
475          Angola                      29.213038     16412.0   

     Exportations - Quantité  % Export/Production  
110                      2.0                  NaN  
203                      NaN                  NaN  
295                      NaN                  NaN  
390                     14.0                  NaN  
475                      0.0                  0.0

In [120]:
manioc_prodexport.sort_values("Production", ascending = False).head(10)

Pays  Proportion sous-nutrition (%)  Production  \
9830      Nigéria                       8.558164     53000.0   
13809   Thaïlande                       9.098311     30228.0   
6334    Indonésie                       8.895762     23937.0   
2129       Brésil                            NaN     21226.0   
475        Angola                      29.213038     16412.0   
5255        Ghana                       7.140805     15990.0   
9376   Mozambique                      23.082260     10000.0   
14743    Viet Nam                       9.806882      9758.0   
2665     Cambodge                      13.975467      8000.0   
6238         Inde                      15.911407      7237.0   

       Exportations - Quantité  % Export/Production  
9830                      11.0             0.020755  
13809                  25214.0            83.412730  
6334                     820.0             3.425659  
2129                      38.0             0.179026  
475                        0.0             0.000000  
5255                       9.0             0.056285  
9376                       0.0             0.000000  
14743                   8973.0            91.955319  
2665                     254.0             3.175000  
6238                      21.0             0.290175

In [121]:
manioc_prodexport.sort_values("Exportations - Quantité", ascending = False).head(10)

Pays  Proportion sous-nutrition (%)  Production  \
13809                  Thaïlande                       9.098311     30228.0   
14743                   Viet Nam                       9.806882      9758.0   
6334                   Indonésie                       8.895762     23937.0   
2665                    Cambodge                      13.975467      8000.0   
10752                   Paraguay                       7.680166      2800.0   
3698                  Costa Rica                       4.217535       145.0   
3228   Chine, Taiwan Province de                       3.842610        15.0   
3043    Chine - RAS de Hong-Kong                            NaN         NaN   
10386                    Ouganda                            NaN      2979.0   
3323         Chine, continentale                            NaN      4585.0   

       Exportations - Quantité  % Export/Production  
13809                  25214.0            83.412730  
14743                   8973.0            91.955319  
6334                     820.0             3.425659  
2665                     254.0             3.175000  
10752                    164.0             5.857143  
3698                     123.0            84.827586  
3228                      82.0           546.666667  
3043                      80.0                  NaN  
10386                     47.0             1.577711  
3323                      41.0             0.894220

In [122]:
manioc_prodexport.sort_values("% Export/Production", ascending = False).head(10)

Pays  Proportion sous-nutrition (%)  Production  \
3228   Chine, Taiwan Province de                       3.842610        15.0   
14743                   Viet Nam                       9.806882      9758.0   
3698                  Costa Rica                       4.217535       145.0   
13809                  Thaïlande                       9.098311     30228.0   
2033           Brunéi Darussalam                            NaN         3.0   
9108                     Mexique                       4.123636        24.0   
15294                   Équateur                      14.642711        46.0   
4700                       Fidji                       0.000000        74.0   
6049                    Honduras                      19.321429        24.0   
8378                    Malaisie                       3.393405        63.0   

       Exportations - Quantité  % Export/Production  
3228                      82.0           546.666667  
14743                   8973.0            91.955319  
3698                     123.0            84.827586  
13809                  25214.0            83.412730  
2033                       1.0            33.333333  
9108                       5.0            20.833333  
15294                      8.0            17.391304  
4700                       7.0             9.459459  
6049                       2.0             8.333333  
8378                       4.0             6.349206

**La Thaïlande est :**

- le pays le plus exportateur de manioc


- le 2e pays le plus producteur de manioc derrière le Nigéria (qui n'exporte très peu)


- Le 4e pays en terme de proportion d'exportation par rapport à la production avec 83.4% (on remarque un cas insolite avec Taiwain qui exporte pour 547% de ce qu'il produit)





In [123]:
dispo.loc[dispo['Pays']=='Thaïlande'].sort_values('Disponibilité intérieure',ascending = False).head(10)

Pays             Produit   Origine  Aliments pour animaux  \
13843  Thaïlande        Sucre, canne  vegetale                    NaN   
13837  Thaïlande    Riz (Eq Blanchi)  vegetale                 2405.0   
13809  Thaïlande              Manioc  vegetale                 1800.0   
13810  Thaïlande                Maïs  vegetale                 3724.0   
13783  Thaïlande      Fruits, Autres  vegetale                    NaN   
13807  Thaïlande     Légumes, Autres  vegetale                    0.0   
13841  Thaïlande       Sucre Eq Brut  vegetale                    NaN   
13806  Thaïlande  Lait - Excl Beurre   animale                    NaN   
13769  Thaïlande               Bière  vegetale                    NaN   
13770  Thaïlande                 Blé  vegetale                 1130.0   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13843                  NaN                                            49.0   
13837                  NaN                                          1139.0   
13809               2081.0                                            40.0   
13810                  NaN                                            95.0   
13783                  NaN                                            63.0   
13807                  NaN                                            36.0   
13841                  NaN                                           368.0   
13806                147.0                                            45.0   
13769                  NaN                                            41.0   
13770                  NaN                                            76.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13843                                              61.11        
13837                                             114.57        
13809                                              13.00        
13810                                              10.16        
13783                                              57.56        
13807                                              47.86        
13841                                              37.69        
13806                                              29.35        
13769                                              30.44        
13770                                              10.93        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13843                                               0.33               
13837                                               2.50               
13809                                               0.05               
13810                                               1.04               
13783                                               0.56               
13807                                               0.32               
13841                                                NaN               
13806                                               1.74               
13769                                                NaN               
13770                                               0.23               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13843                                               0.17          
13837                                              19.97          
13809                                               0.14          
13810                                               2.46          
13783                                               0.72          
13807                                               1.85          
13841                                                NaN          
13806                                               2.46          
13769                                               0.42          
13770                                               2.18          

       Disponibilité intérieure  Exportations - Quantité  \
13843                  100096.0           

In [124]:
dispo.loc[dispo['Pays']=='Thaïlande'].sort_values('Nourriture',ascending = False).head(10)

Pays              Produit   Origine  Aliments pour animaux  \
13837  Thaïlande     Riz (Eq Blanchi)  vegetale                 2405.0   
13843  Thaïlande         Sucre, canne  vegetale                    NaN   
13783  Thaïlande       Fruits, Autres  vegetale                    NaN   
13807  Thaïlande      Légumes, Autres  vegetale                    0.0   
13841  Thaïlande        Sucre Eq Brut  vegetale                    NaN   
13769  Thaïlande                Bière  vegetale                    NaN   
13806  Thaïlande   Lait - Excl Beurre   animale                    NaN   
13767  Thaïlande              Bananes  vegetale                    NaN   
13850  Thaïlande  Viande de Volailles   animale                    NaN   
13849  Thaïlande     Viande de Suides   animale                    NaN   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13837                  NaN                                          1139.0   
13843                  NaN                                            49.0   
13783                  NaN                                            63.0   
13807                  NaN                                            36.0   
13841                  NaN                                           368.0   
13769                  NaN                                            41.0   
13806                147.0                                            45.0   
13767                  NaN                                            26.0   
13850                  NaN                                            52.0   
13849                  NaN                                           124.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13837                                             114.57        
13843                                              61.11        
13783                                              57.56        
13807                                              47.86        
13841                                              37.69        
13769                                              30.44        
13806                                              29.35        
13767                                              15.11        
13850                                              13.69        
13849                                              13.00        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13837                                               2.50               
13843                                               0.33               
13783                                               0.56               
13807                                               0.32               
13841                                                NaN               
13769                                                NaN               
13806                                               1.74               
13767                                               0.08               
13850                                               3.62               
13849                                              11.83               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13837                                              19.97          
13843                                               0.17          
13783                                               0.72          
13807                                               1.85          
13841                                                NaN          
13769                                               0.42          
13806                                               2.46          
13767                                               0.33          
13850                                               4.49          
13849                                               3.92          

       Disponibilité intérieure  Exportations - Quantité  \
13837                   13605.0

In [125]:
dispo.loc[dispo['Pays']=='Thaïlande'].sort_values('Production',ascending = False).head(10)

Pays           Produit   Origine  Aliments pour animaux  \
13843  Thaïlande      Sucre, canne  vegetale                    NaN   
13809  Thaïlande            Manioc  vegetale                 1800.0   
13837  Thaïlande  Riz (Eq Blanchi)  vegetale                 2405.0   
13841  Thaïlande     Sucre Eq Brut  vegetale                    NaN   
13783  Thaïlande    Fruits, Autres  vegetale                    NaN   
13810  Thaïlande              Maïs  vegetale                 3724.0   
13807  Thaïlande   Légumes, Autres  vegetale                    0.0   
13769  Thaïlande             Bière  vegetale                    NaN   
13763  Thaïlande            Ananas  vegetale                    NaN   
13797  Thaïlande    Huile de Palme  vegetale                    NaN   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13843                  NaN                                            49.0   
13809               2081.0                                            40.0   
13837                  NaN                                          1139.0   
13841                  NaN                                           368.0   
13783                  NaN                                            63.0   
13810                  NaN                                            95.0   
13807                  NaN                                            36.0   
13769                  NaN                                            41.0   
13763                  NaN                                            10.0   
13797               1239.0                                            67.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13843                                              61.11        
13809                                              13.00        
13837                                             114.57        
13841                                              37.69        
13783                                              57.56        
13810                                              10.16        
13807                                              47.86        
13769                                              30.44        
13763                                              10.02        
13797                                               2.79        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13843                                               0.33               
13809                                               0.05               
13837                                               2.50               
13841                                                NaN               
13783                                               0.56               
13810                                               1.04               
13807                                               0.32               
13769                                                NaN               
13763                                               0.04               
13797                                               7.56               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13843                                               0.17          
13809                                               0.14          
13837                                              19.97          
13841                                                NaN          
13783                                               0.72          
13810                                               2.46          
13807                                               1.85          
13769                                               0.42          
13763                                               0.08          
13797                                               0.01          

       Disponibilité intérieure  Exportations - Quantité  \
13843                  100096.0                      0.0   
1380

In [126]:
dispo.loc[dispo['Pays']=='Thaïlande'].sort_values('Disponibilité alimentaire (Kcal/personne/jour)',ascending = False).head(10)

Pays               Produit   Origine  Aliments pour animaux  \
13837  Thaïlande      Riz (Eq Blanchi)  vegetale                 2405.0   
13841  Thaïlande         Sucre Eq Brut  vegetale                    NaN   
13849  Thaïlande      Viande de Suides   animale                    NaN   
13810  Thaïlande                  Maïs  vegetale                 3724.0   
13771  Thaïlande  Boissons Alcooliques  vegetale                    NaN   
13770  Thaïlande                   Blé  vegetale                 1130.0   
13799  Thaïlande         Huile de Soja  vegetale                    NaN   
13797  Thaïlande        Huile de Palme  vegetale                    NaN   
13783  Thaïlande        Fruits, Autres  vegetale                    NaN   
13850  Thaïlande   Viande de Volailles   animale                    NaN   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13837                  NaN                                          1139.0   
13841                  NaN                                           368.0   
13849                  NaN                                           124.0   
13810                  NaN                                            95.0   
13771                  NaN                                            83.0   
13770                  NaN                                            76.0   
13799                  NaN                                            73.0   
13797               1239.0                                            67.0   
13783                  NaN                                            63.0   
13850                  NaN                                            52.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13837                                             114.57        
13841                                              37.69        
13849                                              13.00        
13810                                              10.16        
13771                                              10.23        
13770                                              10.93        
13799                                               3.03        
13797                                               2.79        
13783                                              57.56        
13850                                              13.69        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13837                                               2.50               
13841                                                NaN               
13849                                              11.83               
13810                                               1.04               
13771                                                NaN               
13770                                               0.23               
13799                                               8.31               
13797                                               7.56               
13783                                               0.56               
13850                                               3.62               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13837                                              19.97          
13841                                                NaN          
13849                                               3.92          
13810                                               2.46          
13771                                                NaN          
13770                                               2.18          
13799                                                NaN          
13797                                               0.01          
13783                                               0.72          
13850                                               4.49          

       Disponibilité intérieure  Exportations - Quantité  \
13837               

- Le Manioc est le 2e produit, derriere le sucre de canne, que produit le plus le Thailande, il est suivi du riz blanchi


- C'est ce même top 3 qui constitue le top 3 en disponibilité alimentaire de la Thailande


- Par contre le manioc ne fait plus partie du top 10 en disponibilité nourriture (riz blanchi 1er et sucre de cannes 2e)


- Idem pour la disponibilité alimentaire





In [127]:
dispo.loc[(dispo['Pays']=='Thaïlande') & (dispo['Produit']=='Manioc')]

Pays Produit   Origine  Aliments pour animaux  \
13809  Thaïlande  Manioc  vegetale                 1800.0   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
13809               2081.0                                            40.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
13809                                               13.0        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
13809                                               0.05               

       Disponibilité de protéines en quantité (g/personne/jour)  \
13809                                               0.14          

       Disponibilité intérieure  Exportations - Quantité  \
13809                    6264.0                  25214.0   

       Importations - Quantité  Nourriture  Pertes  Production  Semences  \
13809                   1250.0       871.0  1511.0     30228.0       NaN   

       Traitement  Variation de stock  
13809         0.0                 0.0

In [128]:
dispo.loc[(dispo['Pays']=='Nigéria') & (dispo['Produit']=='Manioc')]

Pays Produit   Origine  Aliments pour animaux  Autres Utilisations  \
9830  Nigéria  Manioc  vegetale                26288.0                  NaN   

      Disponibilité alimentaire (Kcal/personne/jour)  \
9830                                           262.0   

      Disponibilité alimentaire en quantité (kg/personne/an)  \
9830                                             118.86        

      Disponibilité de matière grasse en quantité (g/personne/jour)  \
9830                                               0.58               

      Disponibilité de protéines en quantité (g/personne/jour)  \
9830                                               1.22          

      Disponibilité intérieure  Exportations - Quantité  \
9830                   53004.0                     11.0   

      Importations - Quantité  Nourriture  Pertes  Production  Semences  \
9830                     15.0     20636.0  6080.0     53000.0       NaN   

      Traitement  Variation de stock  
9830         0.0                 0.0

On notera également que la quantité de Manioc utilisée par la Thaïlande est de :

- 871 tonnes pour l'alimentation humaine

- 1800 tonnes pour l'alimentation animale

- 2081 tonnes pour d'autres utilisations

- 1511 tonnes perdues

**La Thaïlande est un très grand producteur de manioc, mais surtout un grand exportateur et son utilisation est peu dédiée à l'alimentation humaine, ce qui constraste avec l'autre grand producteur de manioc, le Nigéria, qui l'exporte très peu et l'utilise en grande partie pour l'alimentation humaine et animale**

&nbsp; 

# <font color=#2921CA> CONCLUSION 

&nbsp; 

**Pour l'année 2017 :** 

- La population mondiale était de **7.6 Md** de personnes dont **0.5 Md** en état de sous-nutrition (soit **7.1 %**)


- Le nombre théorique de personnes potentiellement nourries serait de **8.9 ou 9.3 Md** (soit **118 ou 123 %** de la popualtion mondiale)


- Pour les produits d'origine végétale, ce nombre serait de **7.3 ou 7.7** Md (soit **97 ou 102 %** de la population mondiale).        
Ils constitueraient **82 %** de la nutrition mondiale  


&nbsp;

La **disponibilité intérieure** mondiale est constitué de **86 %** de produits d'origine végétale et **14 %** de produits d'origine animale et il y a :


- **50 %** d'utilisation pour l'alimentation des humains (**2 fois + importante** chez origine animale / origine végétale)


- **13%** d'utilisation pour l'alimentation des animaux (**1.8 fois - importante** chez origine animale / origine végétale) 


- **5%** de pertes (**2.9 fois - importante** chez origine animale / origine végétale)

&nbsp;

**A noter :**


Disponibilité intérieure = Nourriture + Pertes + Traitement + Semences + Aliments animaux + Autres utilisations

    et
 
Disponibilité intérieure = Production + Importations - Exportations + Variation de stocks    
    
&nbsp;

    
**Suite des recherches de Julien**

*Utilisation des céréales :*
    
- 42.75 % pour l'alimentation humaine
    
    
- 36.29 % pour l'alimentation des animaux
    

- Riz, Millet, Blé (à plus de 67%) sont utilisés pour l'alimentation des humains 


- Avoine, Orge, Autres (à plus de 65%) sont utilisés pour l'alimentation des animaux


- Les pays dont la part pour l'alimentation des humains figure dans les moins importante sont souvent ceux dont la part pour l'alimentation des animaux figure dans les plus importantes (avec une majorité de pays occidentaux)

&nbsp;

*Thaïlande et manioc :*
    
    
- 9.1 % population en sous-nutrition    
    

- 2e producteur mondial de manioc


- 1er exportateur mondial manioc (83.4% de la production)
    
    
- l'alimentation des humains < les pertes < l'alimentation animale < les autres utilisation
    
    
    